### PR TITLE
Julia implementations

### PR DESCRIPTION
**Pull request by atthom**
Two implementation in Julia based on the Python code.
I tried to be as close as possible as the python code. 
Om my CPU, naive implementation takes 1.2s and the one based on numpy takes 450ms

### CODE REVIEW

**Comment by jinyus** [comment]
Hey, thanks for the PR, could you modify the code to just execute the script and not run the benchmark? I know nothing about julia so it'd be great if you edited the run.sh file to include a function for it.

**Comment by atthom** [comment]
Sure, I will update the run.sh

**Comment by jinyus** [comment]
Hey, also remember to install the deps in the script. Similar to how the run_python_np function is done.

**Comment by jinyus** [comment]
is there a way to install the needed packages from the command line? I had to open the julia shell in stall them

**Comment by atthom** [comment]
I updated the script and the run.sh to install the packages

**Pull request merged**
