### PR TITLE
[SKIP] Update Benchmark Results (Azure F4s-v2-4vCPU-8GB-RAM))

### PR DESCRIPTION
**Pull request by jinyus**
Automated PR

### CODE REVIEW

**Comment by algunion** [comment]
It seems that Julia's warmup is lost. 

Should we do some precompiling, or will the internal warmup call be enough?

**Comment by jinyus** [comment]
Precompiling would be great.

**Comment by jinyus** [comment]
I'm not going to merge this. I re-added the manual warm up and running again

**Comment by jinyus** [comment]
Julia is on top now. Impressive.

**Pull request merged**
