### PR TITLE
clojure: limit jvm warmup phase

### PR DESCRIPTION
**Pull request by leetwinski**
this one limits the warmup phase to 5000 posts, decreasing total run time

as an interesting consequence it also slightly speeds up larger data processing (at least on my machine)

### CODE REVIEW

**Comment by jinyus** [comment]
Seeing the same speed up...I will try that on the other vm langs.

Main:
```
| Clojure | 96.90 ms | 1.08 s | 8.89 s | 10.06 s |
```

This PR:
```yaml
Clojure:

        Processing time (w/o IO): 97ms
        total: 0.88s memory: 121560k
        Processing time (w/o IO): 98ms
        total: 0.88s memory: 121332k
        Processing time (w/o IO): 98ms
        total: 0.87s memory: 125284k
        Processing time (w/o IO): 99ms
        total: 0.86s memory: 123024k
        Processing time (w/o IO): 96ms
        total: 0.87s memory: 123204k
        Processing time (w/o IO): 101ms
        total: 0.88s memory: 125436k
        Processing time (w/o IO): 99ms
        total: 0.88s memory: 124372k
        Processing time (w/o IO): 96ms
        total: 0.88s memory: 128368k
        Processing time (w/o IO): 98ms
        total: 0.86s memory: 123872k
        Processing time (w/o IO): 98ms
        total: 0.86s memory: 122432k

Clojure:

        Processing time (w/o IO): 1106ms
        total: 2.05s memory: 188796k
        Processing time (w/o IO): 1097ms
        total: 2.06s memory: 182020k
        Processing time (w/o IO): 1083ms
        total: 2.05s memory: 190136k

Clojure:

        Processing time (w/o IO): 9262ms
        total: 10.59s memory: 354256k
        Processing time (w/o IO): 9050ms
        total: 10.31s memory: 331320k
        Processing time (w/o IO): 9054ms
        total: 10.34s memory: 369572k
```

**Comment by leetwinski** [comment]
thanks!
that must be because of the uncertain nature of jvm's jit.. It can vary, i guess. 
Just wanted to decrease total time for large collections,.

**Comment by jinyus** [comment]
Running main now shows ~9s so it's not far off.

**Comment by leetwinski** [comment]
i was addressing this one

(this one is from yesterday's pr)
```
rocessing time (w/o IO): 8871ms
        total: 19.02s memory: 332340k
        Processing time (w/o IO): 9052ms
        total: 19.31s memory: 335032k
        Processing time (w/o IO): 8736ms
        total: 18.63s memory: 338596k
```

so, the total here is 18-19s , and now 10s, 
because i removed insanely long warmup phase for huge collections.
thought that waiting 10 extra seconds (unneeded) for every execution was annoying
))

**Pull request merged**
