### PR TITLE
Common Lisp first scratch

### PR DESCRIPTION
**Pull request by NoobsEnslaver**

### CODE REVIEW

**Comment by jinyus** [comment]
It's outputting the time in seconds and doesn't have decimals.

```
Common Lisp (SBCL):

        Posts readed: 5000
        Processing time (w/o IO): 0 s
        Processing time total: 0 ms
        total: 0.32s memory: 117608k
        Posts readed: 5000
        Processing time (w/o IO): 1 s
        Processing time total: 1 ms
        total: 0.32s memory: 115196k
        Posts readed: 5000
        Processing time (w/o IO): 0 s
        Processing time total: 0 ms
        total: 0.33s memory: 113544k
        Posts readed: 5000
        Processing time (w/o IO): 0 s
        Processing time total: 0 ms
        total: 0.33s memory: 113552k
        Posts readed: 5000
        Processing time (w/o IO): 0 s
        Processing time total: 1 ms
        total: 0.32s memory: 117740k
        Posts readed: 5000
        Processing time (w/o IO): 0 s
        Processing time total: 0 ms
        total: 0.33s memory: 115200k
        Posts readed: 5000
        Processing time (w/o IO): 0 s
        Processing time total: 0 ms
        total: 0.32s memory: 117612k
        Posts readed: 5000
        Processing time (w/o IO): 0 s
        Processing time total: 1 ms
        total: 0.33s memory: 115568k
        Posts readed: 5000
        Processing time (w/o IO): 0 s
        Processing time total: 0 ms
        total: 0.33s memory: 113552k
        Posts readed: 5000
        Processing time (w/o IO): 0 s
        Processing time total: 0 ms
        total: 0.32s memory: 115196k
```

**Comment by jinyus** [comment]
Also getting an error on subsequent runs. Maybe install the deps outside of the script?

```
   source: (ERROR "Quicklisp has already been installed. Load ~S instead."
                  SETUP-FILE)
```

**Comment by NoobsEnslaver** [comment]
> Also getting an error on subsequent runs. Maybe install the deps outside of the script?
> 
> ```
>    source: (ERROR "Quicklisp has already been installed. Load ~S instead."
>                   SETUP-FILE)
> ```

hm.. how? i run many times `./run.sh cl` and all ok. We may move quicklisp installation to user and just expect it installed, but i want make it little easy.

**Comment by jinyus** [comment]
Which OS are you on? Still having issues:

```
This is SBCL 2.3.11, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.

  ==== quicklisp quickstart 2015-01-28 loaded ====

    To continue with installation, evaluate: (quicklisp-quickstart:install)

    For installation options, evaluate: (quicklisp-quickstart:help)

While evaluating the form starting at line 5, column 0
  of #P"/home/dev/projects/go/lisp/common-lisp/related.lisp":
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD tid=189140 "main thread" RUNNING
                                    {10047F81D3}>:
  Quicklisp has already been installed. Load #P"/home/dev/quicklisp/setup.lisp" instead.

Backtrace for: #<SB-THREAD:THREAD tid=189140 "main thread" RUNNING {10047F81D3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "Quicklisp has already been installed. Load ~S instead." {1002459563}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "Quicklisp has already been installed. Load ~S instead." {1002459563}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "Quicklisp has already been installed. Load ~S instead." {1002459563}>)
3: (ERROR #<SIMPLE-ERROR "Quicklisp has already been installed. Load ~S instead." {1002459563}>)
4: (SB-KERNEL:WITH-SIMPLE-CONDITION-RESTARTS ERROR NIL "Quicklisp has already been installed. Load ~S instead." #P"/home/dev/quicklisp/setup.lisp")
5: (QUICKLISP-QUICKSTART:INSTALL :PATH NIL :PROXY NIL :CLIENT-URL NIL :CLIENT-VERSION NIL :DIST-URL NIL :DIST-VERSION NIL)
6: (SB-INT:SIMPLE-EVAL-IN-LEXENV (QUICKLISP-QUICKSTART:INSTALL) #<NULL-LEXENV>)
7: (SB-INT:SIMPLE-EVAL-IN-LEXENV (UNLESS (FIND-PACKAGE (QUOTE #:QL)) (QUICKLISP-QUICKSTART:INSTALL)) #<NULL-LEXENV>)
8: (EVAL-TLF (UNLESS (FIND-PACKAGE (QUOTE #:QL)) (QUICKLISP-QUICKSTART:INSTALL)) 1 NIL)
9: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (UNLESS (FIND-PACKAGE (QUOTE #:QL)) (QUICKLISP-QUICKSTART:INSTALL)) 1)
10: ((LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) (UNLESS (FIND-PACKAGE (QUOTE #:QL)) (QUICKLISP-QUICKSTART:INSTALL)) :CURRENT-INDEX 1)
11: (SB-C::%DO-FORMS-FROM-INFO #<FUNCTION (LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) {7F449A9874CB}> #<SB-C::SOURCE-INFO {100144DE33}> SB-C::INPUT-ERROR-IN-LOAD)
12: (SB-INT:LOAD-AS-SOURCE #<SB-INT:FORM-TRACKING-STREAM for "file /home/dev/projects/go/lisp/common-lisp/related.lisp" {10014412D3}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
13: ((LABELS SB-FASL::LOAD-STREAM-1 :IN LOAD) #<SB-INT:FORM-TRACKING-STREAM for "file /home/dev/projects/go/lisp/common-lisp/related.lisp" {10014412D3}> NIL)
14: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<FUNCTION (LABELS SB-FASL::LOAD-STREAM-1 :IN LOAD) {7F449A98788B}> #<SB-INT:FORM-TRACKING-STREAM for "file /home/dev/projects/go/lisp/common-lisp/related.lisp" {10014412D3}> NIL #<SB-INT:FORM-TRACKING-STREAM for "file /home/dev/projects/go/lisp/common-lisp/related.lisp" {10014412D3}>)
15: (LOAD #P"related.lisp" :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST :ERROR :EXTERNAL-FORMAT :DEFAULT)
16: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:LOAD . "related.lisp") (:QUIT)))
17: (SB-IMPL::TOPLEVEL-INIT)
18: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
19: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-IMPL::START-LISP))
20: (SB-IMPL::%START-LISP)

unhandled condition in --disable-debugger mode, quitting
```

**Comment by NoobsEnslaver** [comment]
Ok, let just expect `quicklisp` in user machine. I update README.md and remove quicklisp and related logic from script

**Comment by jinyus** [comment]
Sorry for the delay, I couldn't get this to work in linux so I will merge and add it to the table when I get docker working.

**Comment by NoobsEnslaver** [comment]
@jinyus did you try
   ```bash
   > wget https://beta.quicklisp.org/quicklisp.lisp &&
   > sbcl --load quicklisp.lisp --non-interactive --eval '(quicklisp-quickstart:install)' --eval '(ql:add-to-init-file)'
   <Enter>
   ```
?

**Comment by jinyus** [comment]
Got it working. But getting a stackoverflow error on last round: #493

**Comment by NoobsEnslaver** [comment]
how generate 60k posts? Or, send it here plz. I just copy content of original 5k posts upto 60k - works fine @jinyus

**Comment by jinyus** [comment]
```bash
python gen_fake_posts.py 60000
```

**Pull request merged**
