### PR TITLE
[rust] Some minor optimizations

### PR DESCRIPTION
**Pull request by cloneable**
* Switch tag indices to u8 like D has.
* Make Post more cache line friendly.
* Use SmallVec to store str references inline.
* rust_con: Use local ThreadPool and initialize post-count TLS.
* Some cleanups.

### CODE REVIEW

**Comment by cyrusmsk** [comment]
Btw can we remove this "mimalloc" thing from Rust code?
I suppose almost every compiled language could make some changes in default allocators settings. But except Rust nobody is doing it.
Of course mimalloc is a great thing, but I don't think it should be applied only for Rust
@jinyus

**Comment by cyrusmsk** [comment]
> Move tag lookup table creation before counter like other languages.

This was also fixed in D. Now lookup table created after the counter.

**Comment by cyrusmsk** [comment]
Thanks!

**Comment by jinyus** [comment]
It seems smallvec invokes unsafe code: https://docs.rs/smallvec/latest/src/smallvec/lib.rs.html#7-2463

**Comment by cloneable** [comment]
Lots of things contain unsafe code. There's nothing wrong with unsafe code, provided UB soundness is checked. smallvec is a very popular crate. But I can understand why the benchmark code itself should not resort to unsafe code.

**Comment by jinyus** [comment]
That's a slippery slope. It's better to ban unsafe code outright.

**Comment by jinyus** [comment]
wish you have made smaller commits so I can cherry pick them. I will try to merge manually.

**Pull request closed without merging**
