### PR TITLE
port fsharp to ocaml

### PR DESCRIPTION
**Pull request by mvikto**

### CODE REVIEW

**Comment by jinyus** [comment]
Hey, I can't get this to build.

```
File "bin/dune", line 4, characters 24-51:
4 |  (libraries yojson core ppx_deriving_yojson.runtime)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Library "ppx_deriving_yojson.runtime" not found.
-> required by _build/default/bin/main.exe
-> required by _build/install/default/bin/okaml


File "bin/dune", line 5, characters 18-35:  
5 |  (preprocess (pps ppx_deriving.show ppx_deriving_yojson)))
                      ^^^^^^^^^^^^^^^^^
Error: Library "ppx_deriving.show" not found.
-> required by _build/default/bin/main.pp.ml
```

I'm using dune3.8 on linux

**Comment by mvikto** [comment]
Hey can you try please running `opam install . --deps-only` and then try again?

**Comment by jinyus** [comment]
This is the output:

```
[WARNING] Failed checks on okaml package definition from source at file:///home/jinyus/projects/mlpr/ocaml:
  warning 62: License doesn't adhere to the SPDX standard, see https://spdx.org/licenses/: "LICENSE"
Nothing to do.
```

running again produces:

```
# Run eval $(opam env) to update the current shell environment
File "_none_", line 1:              
Alert ocaml_deprecated_auto_include: 
OCaml's lib directory layout changed in 5.0. The unix subdirectory has been
automatically added to the search path, but you should add -I +unix to the
command-line to silence this alert (e.g. by adding unix to the list of
libraries in your dune file, or adding use_unix to your _tags file for
ocamlbuild, or using -package unix for ocamlfind).
File "_none_", line 1:             
Error: No implementations provided for the following modules:
         Unix referenced from bin/.main.eobjs/native/dune__exe__Main.cmx
```

**Comment by jinyus** [comment]
Hey, I'm going to improve how benchmarks are ran to make it reproducible. Just provide a docker file at `./ocaml/Dockerfile`

**Pull request merged**
