### PR TITLE
Clean up some rust

### PR DESCRIPTION
**Pull request by masmullin2000**
1) make least_n actually return the least_n values for any item type that uses 'normal' ordering
1a) PostCount now orders 'normally'
2) use utils::fill_post_count() - the functional methodology works just as fast as the direct for loop method and makes things cleaner

### CODE REVIEW

**Comment by jinyus** [comment]
Let me know when you're ready to merge

**Comment by masmullin2000** [comment]
Ready to be reviewed.

**Comment by jinyus** [comment]
Every run is fresh in docker so I don't think there's a need to run `cargo update`

Main branch:
```
Rust | 23.66 ms | 340.94 ms | 3.03 s
```

This PR:
```
Rust:

        Benchmark 1: ./target/release/rust
        Processing time (w/o IO): 24.12615ms
        Processing time (w/o IO): 23.934247ms
        Processing time (w/o IO): 23.969248ms
        Processing time (w/o IO): 24.003048ms
        Processing time (w/o IO): 23.918947ms
        Processing time (w/o IO): 24.020249ms
        Processing time (w/o IO): 24.001148ms
        Processing time (w/o IO): 24.09395ms
        Processing time (w/o IO): 23.981847ms
        Processing time (w/o IO): 24.025648ms
        Processing time (w/o IO): 23.943347ms
        Processing time (w/o IO): 24.003948ms
        Processing time (w/o IO): 24.12235ms
          Time (mean ± σ):      38.5 ms ±   0.4 ms    [User: 32.5 ms, System: 6.0 ms]
          Range (min … max):    38.1 ms …  39.1 ms    10 runs
         
Rust:

        Benchmark 1: ./target/release/rust
        Processing time (w/o IO): 352.534049ms
        Processing time (w/o IO): 352.463625ms
        Processing time (w/o IO): 352.078818ms
          Time (mean ± σ):     411.4 ms ±   0.4 ms    [User: 385.9 ms, System: 25.4 ms]
          Range (min … max):   411.1 ms … 411.6 ms    2 runs
         
Rust:

        Benchmark 1: ./target/release/rust
        Processing time (w/o IO): 3.224445841s
        Processing time (w/o IO): 3.197339251s
        Processing time (w/o IO): 3.204087569s
          Time (mean ± σ):      3.407 s ±  0.003 s    [User: 3.300 s, System: 0.095 s]
          Range (min … max):    3.405 s …  3.409 s    2 runs
```

**Comment by jinyus** [comment]
Main Branch:
`Rust Concurrent | 12.28 ms | 174.02 ms | 1.52 s`

This PR:
```
Rust Concurrent:

        Benchmark 1: ./target/release/rust_rayon
        Processing time (w/o IO): 12.373121ms
        Processing time (w/o IO): 11.966613ms
        Processing time (w/o IO): 11.78021ms
        Processing time (w/o IO): 12.038715ms
        Processing time (w/o IO): 11.932512ms
        Processing time (w/o IO): 11.885212ms
        Processing time (w/o IO): 11.980514ms
        Processing time (w/o IO): 11.958613ms
        Processing time (w/o IO): 12.014014ms
        Processing time (w/o IO): 11.904912ms
        Processing time (w/o IO): 11.969414ms
        Processing time (w/o IO): 11.868611ms
        Processing time (w/o IO): 11.938513ms
          Time (mean ± σ):      28.6 ms ±   0.4 ms    [User: 31.2 ms, System: 9.0 ms]
          Range (min … max):    28.2 ms …  29.4 ms    10 runs
         
Rust Concurrent:

        Benchmark 1: ./target/release/rust_rayon
        Processing time (w/o IO): 171.533655ms
        Processing time (w/o IO): 173.560792ms
        Processing time (w/o IO): 173.226086ms
          Time (mean ± σ):     239.3 ms ±   0.8 ms    [User: 387.7 ms, System: 21.1 ms]
          Range (min … max):   238.7 ms … 239.8 ms    2 runs
         
Rust Concurrent:

        Benchmark 1: ./target/release/rust_rayon
        Processing time (w/o IO): 1.495971851s
        Processing time (w/o IO): 1.491662337s
        Processing time (w/o IO): 1.4936777s
          Time (mean ± σ):      1.723 s ±  0.028 s    [User: 3.108 s, System: 0.075 s]
          Range (min … max):    1.703 s …  1.742 s    2 runs
```

**Comment by jinyus** [comment]
So rust_con is a bit faster, but the single threaded version is consistently slower (ran 3 times). If you want to run `cargo update`. You'd have to put it in `run.sh` before compilation.

**Comment by jinyus** [comment]
Same number after adding cargo update:

```
Rust:

        Benchmark 1: ./target/release/rust
        Processing time (w/o IO): 24.223482ms
        Processing time (w/o IO): 24.011178ms
        Processing time (w/o IO): 24.051379ms
        Processing time (w/o IO): 24.043778ms
        Processing time (w/o IO): 24.056979ms
        Processing time (w/o IO): 24.015478ms
        Processing time (w/o IO): 23.976077ms
        Processing time (w/o IO): 24.033678ms
        Processing time (w/o IO): 24.078479ms
        Processing time (w/o IO): 24.020578ms
        Processing time (w/o IO): 24.052278ms
        Processing time (w/o IO): 24.017878ms
        Processing time (w/o IO): 24.010678ms
          Time (mean ± σ):      39.7 ms ±   0.5 ms    [User: 33.8 ms, System: 6.0 ms]
          Range (min … max):    39.0 ms …  40.7 ms    10 runs
         
Rust:

        Benchmark 1: ./target/release/rust
        Processing time (w/o IO): 352.62372ms
        Processing time (w/o IO): 353.223437ms
        Processing time (w/o IO): 352.958932ms
          Time (mean ± σ):     414.1 ms ±   0.8 ms    [User: 392.5 ms, System: 21.5 ms]
          Range (min … max):   413.6 ms … 414.7 ms    2 runs
         
Rust:

        Benchmark 1: ./target/release/rust
        Processing time (w/o IO): 3.184189139s
        Processing time (w/o IO): 3.219412412s
        Processing time (w/o IO): 3.213165537s
          Time (mean ± σ):      3.428 s ±  0.001 s    [User: 3.337 s, System: 0.085 s]
          Range (min … max):    3.428 s …  3.429 s    2 runs
```

**Comment by masmullin2000** [comment]
Sorry, we have a misunderstanding.  I do not suggest that cargo update be done via automation, what I am saying is that, as part of the update, I did a manual cargo update, which is the cause of the slowdown.

If you take the code from the main branch (your current code without these changes), and run a cargo update, then do a benchmark run, you will see a slowdown similar to what we see here (at least thats what I observed).

Rust projects _should not_ do a cargo update via automation, as it can lead to compile breaks in CI (though extremely unlikely, it has happened).  However, developers of a rust project should periodically do a cargo update manually to ensure that bug fixes are picked up.

**Comment by masmullin2000** [comment]
I put bumpalo back.  Please re-look when you have the time.

**Comment by jinyus** [comment]
Much slower for some reason:

```
Rust:

        Benchmark 1: ./target/release/rust
        Processing time (w/o IO): 29.243333ms
        Processing time (w/o IO): 28.908926ms
        Processing time (w/o IO): 28.886826ms
        Processing time (w/o IO): 29.351936ms
        Processing time (w/o IO): 28.953927ms
        Processing time (w/o IO): 30.43086ms
        Processing time (w/o IO): 28.947027ms
        Processing time (w/o IO): 29.220633ms
        Processing time (w/o IO): 28.977328ms
        Processing time (w/o IO): 29.204633ms
        Processing time (w/o IO): 28.913026ms
        Processing time (w/o IO): 28.975328ms
        Processing time (w/o IO): 29.459239ms
          Time (mean ± σ):      45.3 ms ±   0.8 ms    [User: 37.3 ms, System: 7.9 ms]
          Range (min … max):    43.9 ms …  46.4 ms    10 runs
         
Rust:

        Benchmark 1: ./target/release/rust
        Processing time (w/o IO): 429.429505ms
        Processing time (w/o IO): 428.996796ms
        Processing time (w/o IO): 428.522086ms
          Time (mean ± σ):     493.0 ms ±   1.0 ms    [User: 473.6 ms, System: 19.3 ms]
          Range (min … max):   492.3 ms … 493.7 ms    2 runs
         
Rust:

        Benchmark 1: ./target/release/rust
        Processing time (w/o IO): 3.77049668s
        Processing time (w/o IO): 3.768319074s
        Processing time (w/o IO): 3.787054572s
          Time (mean ± σ):      3.999 s ±  0.014 s    [User: 3.918 s, System: 0.074 s]
          Range (min … max):    3.989 s …  4.009 s    2 runs
```

Here is a fresh run from main branch just to rule out noise:

```
Rust:

        Benchmark 1: ./target/release/rust
        Processing time (w/o IO): 23.476623ms
        Processing time (w/o IO): 23.833129ms
        Processing time (w/o IO): 23.376621ms
        Processing time (w/o IO): 23.694826ms
        Processing time (w/o IO): 25.975267ms
        Processing time (w/o IO): 23.430522ms
        Processing time (w/o IO): 23.568624ms
        Processing time (w/o IO): 23.520923ms
        Processing time (w/o IO): 24.414339ms
        Processing time (w/o IO): 23.735327ms
        Processing time (w/o IO): 23.571324ms
        Processing time (w/o IO): 23.38362ms
        Processing time (w/o IO): 23.480423ms
          Time (mean ± σ):      39.7 ms ±   1.4 ms    [User: 33.1 ms, System: 6.7 ms]
          Range (min … max):    38.4 ms …  43.1 ms    10 runs
         
Rust:

        Benchmark 1: ./target/release/rust
        Processing time (w/o IO): 343.572701ms
        Processing time (w/o IO): 340.852944ms
        Processing time (w/o IO): 355.808858ms
          Time (mean ± σ):     410.1 ms ±  10.5 ms    [User: 380.7 ms, System: 29.4 ms]
          Range (min … max):   402.7 ms … 417.5 ms    2 runs
         
Rust:

        Benchmark 1: ./target/release/rust
        Processing time (w/o IO): 3.046973662s
        Processing time (w/o IO): 3.042152054s
        Processing time (w/o IO): 3.052236393s
          Time (mean ± σ):      3.279 s ±  0.022 s    [User: 3.164 s, System: 0.087 s]
          Range (min … max):    3.263 s …  3.294 s    2 runs

```

**Pull request closed without merging**
