### PR TITLE
Update F# to dotnet 8, add fsharp AOT version

### PR DESCRIPTION
**Pull request by delneg**
https://github.com/jinyus/related_post_gen/pull/198
After C#'s upgrade to dotnet 8 & AOT, it's only fair to do the same for F#

Also, I've added ServerGarbageCollection to match C# version exactly

### CODE REVIEW

**Comment by delneg** [comment]
I've tested now, and looks like AOT is broken for F#.
Trying to fix it, but JSON serialization is still broken

**Comment by delneg** [comment]
Yeah, looks like I've fixed it.
For me it got faster from 32ms to 28-29ms locally

**Comment by delneg** [comment]
Ok, so let me explain the changes made:
1) Had to add .rd.xml file which instructs ILC to not link out the necessary types during AOT compilation
2) Switched JSON ser/de from System.Text.Json (which is not AOT compatible due to sourcegen) for FSharp.Json
3) Update to dotnet 8
4) Enable server GC like in C#
5) add AOT mode to run.sh


I've removed [<Struct>] for RelatedPosts to not impact any performance

**Comment by jinyus** [comment]
What do you use to install dotnet, only v7 is in the arch repo. I need to update the dockerfile

**Comment by delneg** [comment]
You can find installer & binaries here
https://dotnet.microsoft.com/en-us/download/dotnet/8.0

**Comment by delneg** [comment]
Worked for me:
```
wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
chmod +x ./dotnet-install.sh
./dotnet-install.sh --channel 8.0
```

**Pull request merged**
