### PR TITLE
Naive Haskell solution

### PR DESCRIPTION
**Pull request by schoettl**
to be optimized... by more strictness, better data types, etc.

### CODE REVIEW

**Comment by jinyus** [comment]
Hey, it needs to output the processing time:

```ruby
print "Processing time (w/o IO): #{(t2 - t1).total_milliseconds}ms\n"

```

**Comment by schoettl** [comment]
OK. Parsing and encoding JSON does still count as IO, right?

jinyus ***@***.***> schrieb am Di., 17. Okt. 2023, 01:34:

**Comment by schoettl** [comment]
I don't know yet how compute the processing time... Haskell's lazyness does everything inside the `do` block in random order ^^

**Comment by jinyus** [comment]
> OK. Parsing and encoding JSON does still count as IO, right? 

It should exclude json parsing and writing the results to disk.

**Comment by jinyus** [comment]
That behavior is very weird, are you still working on it? I'm not sure I should merge...

**Comment by schoettl** [comment]
Thanks @ozkutuk for the suggestion on how to force evaluation. The timer should now work.

Ready to merge from my side, optimizations can be provided later.

**Pull request merged**
