### PR TITLE
[julia] Refactor julia installation, and benchmark code

### PR DESCRIPTION
**Pull request by MasonProtter**
~~This design uses  a threadsafe task-local-buffer to pre-allocate maxn and maxv on each spawned task. This obviates the need for static arrays and does buffer-reuse instead.~~

~~On my machine I see the runtime of the single threaded code drop from 23ms to 17ms, and the concurrent benchmark drops from 5ms to 3ms. I'll update with better benchmarks once Docker finally finishes setting up on my machine.~~

This refactors the code, changing how Julia is installed to use the official binaries instead of the ones that are incorrectly linked to LLVM, and it bundles the code into a package to use native precompilation instead of manually warming up the analysis functions. This makes it more reproducible, and more in line with how the AOT compiled languages operate. 

There's no significant speed difference that I see locally.

### CODE REVIEW

**Comment by MasonProtter** [comment]
Hmm, that's weird. When I run the Docker benchmarks, I'm seeing a performance regression relative to `main` rather than a performance improvement. Not sure what's up with that, I suspect I'm just doing something wrong with Docker.

**Comment by jinyus** [comment]
Performance is the same on my machine will test on the benchmarking VM

**Comment by jinyus** [comment]
These are the results from the VM:

```
Julia:

        Benchmark 1: julia related.jl
        Processing time (w/o IO): 38 milliseconds
        Processing time (w/o IO): 38 milliseconds
        Processing time (w/o IO): 38 milliseconds
        Processing time (w/o IO): 38 milliseconds
        Processing time (w/o IO): 30 milliseconds
        Processing time (w/o IO): 31 milliseconds
        Processing time (w/o IO): 30 milliseconds
        Processing time (w/o IO): 38 milliseconds
        Processing time (w/o IO): 31 milliseconds
        Processing time (w/o IO): 31 milliseconds
        Processing time (w/o IO): 31 milliseconds
        Processing time (w/o IO): 38 milliseconds
        Processing time (w/o IO): 37 milliseconds
          Time (mean ± σ):      2.762 s ±  0.022 s    [User: 2.585 s, System: 0.176 s]
          Range (min … max):    2.730 s …  2.802 s    10 runs
         
Julia:

        Benchmark 1: julia related.jl
        Processing time (w/o IO): 461 milliseconds
        Processing time (w/o IO): 575 milliseconds
        Processing time (w/o IO): 459 milliseconds
          Time (mean ± σ):      3.852 s ±  0.141 s    [User: 3.643 s, System: 0.207 s]
          Range (min … max):    3.752 s …  3.951 s    2 runs
         
Julia:

        Benchmark 1: julia related.jl
        Processing time (w/o IO): 5052 milliseconds
        Processing time (w/o IO): 5046 milliseconds
        Processing time (w/o IO): 5046 milliseconds
          Time (mean ± σ):     13.294 s ±  0.013 s    [User: 12.972 s, System: 0.311 s]
          Range (min … max):   13.285 s … 13.304 s    2 runs

```

**Comment by MasonProtter** [comment]
Hm that's really interesting that there's such a big difference between the two versions for me when i just invoke `julia related.jl` from the command line. 

I wonder if this has to do with the way julia was installed on the docker system. You installed it using `pacman`, but that's explicitly not recommended because the `pacman` version is compiled against the system LLVM which does not yet have all the bug fixes and patches we are working on upstreaming. See the arch wiki here: https://wiki.archlinux.org/title/Julia:
```quote
Note: The [julia](https://archlinux.org/packages/?name=julia) package is compiled against system libraries and is therefore unsupported by the upstream. While it may be suitable for basic usage it is incompatible with external packages (e.g. MKL, LLVM, LLVMExtra, or packages that depend on these, like CUDA or Flux) which rely on Julia's bundled versions of its dependencies. For example, Sundials.jl (which is a dependency of DifferentialEquations.jl) [fails](https://github.com/SciML/Sundials.jl/issues/358) to precompile with this package, but builds without errors with the official builds. Bugs reported against this binary will be [closed](https://github.com/JuliaLinearAlgebra/MKL.jl/issues/105#issuecomment-1025985667).
```

**Comment by MasonProtter** [comment]
@jinyus, would you mind re-running the benchmark. I want to check if what you see matches what I'm seeing here.

**Comment by jinyus** [comment]
Results Run 1:

```
Julia:

        Benchmark 1: julia related.jl
        Processing time (w/o IO): 32 milliseconds
        Processing time (w/o IO): 31 milliseconds
        Processing time (w/o IO): 32 milliseconds
        Processing time (w/o IO): 39 milliseconds
        Processing time (w/o IO): 39 milliseconds
        Processing time (w/o IO): 39 milliseconds
        Processing time (w/o IO): 31 milliseconds
        Processing time (w/o IO): 39 milliseconds
        Processing time (w/o IO): 31 milliseconds
        Processing time (w/o IO): 38 milliseconds
        Processing time (w/o IO): 38 milliseconds
        Processing time (w/o IO): 38 milliseconds
        Processing time (w/o IO): 39 milliseconds
          Time (mean ± σ):      2.725 s ±  0.024 s    [User: 2.617 s, System: 0.212 s]
          Range (min … max):    2.685 s …  2.761 s    10 runs
         
Julia:

        Benchmark 1: julia related.jl
        Processing time (w/o IO): 576 milliseconds
        Processing time (w/o IO): 459 milliseconds
        Processing time (w/o IO): 462 milliseconds
          Time (mean ± σ):      3.709 s ±  0.016 s    [User: 3.556 s, System: 0.255 s]
          Range (min … max):    3.697 s …  3.720 s    2 runs
         
Julia:

        Benchmark 1: julia related.jl
        Processing time (w/o IO): 3993 milliseconds
        Processing time (w/o IO): 5056 milliseconds
        Processing time (w/o IO): 4002 milliseconds
          Time (mean ± σ):     12.172 s ±  1.471 s    [User: 11.938 s, System: 0.330 s]
          Range (min … max):   11.132 s … 13.212 s    2 runs
         
```

Run 2:

```
Julia:

        Benchmark 1: julia related.jl
        Processing time (w/o IO): 32 milliseconds
        Processing time (w/o IO): 38 milliseconds
        Processing time (w/o IO): 38 milliseconds
        Processing time (w/o IO): 31 milliseconds
        Processing time (w/o IO): 38 milliseconds
        Processing time (w/o IO): 38 milliseconds
        Processing time (w/o IO): 39 milliseconds
        Processing time (w/o IO): 39 milliseconds
        Processing time (w/o IO): 31 milliseconds
        Processing time (w/o IO): 31 milliseconds
        Processing time (w/o IO): 39 milliseconds
        Processing time (w/o IO): 38 milliseconds
        Processing time (w/o IO): 39 milliseconds
          Time (mean ± σ):      2.703 s ±  0.023 s    [User: 2.600 s, System: 0.206 s]
          Range (min … max):    2.666 s …  2.748 s    10 runs
         
Julia:

        Benchmark 1: julia related.jl
        Processing time (w/o IO): 463 milliseconds
        Processing time (w/o IO): 577 milliseconds
        Processing time (w/o IO): 462 milliseconds
          Time (mean ± σ):      3.885 s ±  0.151 s    [User: 3.717 s, System: 0.270 s]
          Range (min … max):    3.778 s …  3.991 s    2 runs
         
Julia:

        Benchmark 1: julia related.jl
        Processing time (w/o IO): 5052 milliseconds
        Processing time (w/o IO): 3999 milliseconds
        Processing time (w/o IO): 5052 milliseconds
          Time (mean ± σ):     12.195 s ±  1.472 s    [User: 11.984 s, System: 0.308 s]
          Range (min … max):   11.154 s … 13.236 s    2 runs

```

**Comment by jinyus** [comment]
old:

```
Julia:

        Benchmark 1: julia related.jl
        Processing time (w/o IO): 38 milliseconds
        Processing time (w/o IO): 31 milliseconds
        Processing time (w/o IO): 30 milliseconds
        Processing time (w/o IO): 38 milliseconds
        Processing time (w/o IO): 31 milliseconds
        Processing time (w/o IO): 38 milliseconds
        Processing time (w/o IO): 38 milliseconds
        Processing time (w/o IO): 38 milliseconds
        Processing time (w/o IO): 30 milliseconds
        Processing time (w/o IO): 38 milliseconds
        Processing time (w/o IO): 38 milliseconds
        Processing time (w/o IO): 38 milliseconds
        Processing time (w/o IO): 38 milliseconds
          Time (mean ± σ):      3.241 s ±  0.022 s    [User: 3.059 s, System: 0.181 s]
          Range (min … max):    3.219 s …  3.282 s    10 runs
         
Julia:

        Benchmark 1: julia related.jl
        Processing time (w/o IO): 575 milliseconds
        Processing time (w/o IO): 574 milliseconds
        Processing time (w/o IO): 576 milliseconds
          Time (mean ± σ):      4.420 s ±  0.024 s    [User: 4.210 s, System: 0.207 s]
          Range (min … max):    4.403 s …  4.436 s    2 runs
         
Julia:

        Benchmark 1: julia related.jl
        Processing time (w/o IO): 3974 milliseconds
        Processing time (w/o IO): 5061 milliseconds
        Processing time (w/o IO): 3978 milliseconds
          Time (mean ± σ):     12.651 s ±  1.521 s    [User: 12.362 s, System: 0.280 s]
          Range (min … max):   11.575 s … 13.727 s    2 runs

```

**Comment by MasonProtter** [comment]
Okay, so the various things I've played around with haven't had a significant performance impact, but I think they're useful.

I've put the julia benchmarks into packages using AOT compilation and  proper dependency tracking. I've also switched the Docker build to use official julia binaries instead of the package manager ones which incorrectly link to the system LLVM.

**Pull request merged**
