### PR TITLE
cpp and cpp_con ref #410 and zig improvement

### PR DESCRIPTION
**Pull request by kaiwu**
not necessarily faster, addresses the concern of bare pointer

### CODE REVIEW

**Comment by jinyus** [comment]
C++ is ~37% faster on the test machine:

```
| C++ (This PR) | 14.00 ms | 174.33 ms | 1.48 s | 1.66 s |

| C++ (Main) | 18.30 ms | 265.33 ms | 2.36 s | 2.64 s |
```

**Comment by kaiwu** [comment]
sorry for the pile ups, was happy copying rust's trick

**Comment by cyrusmsk** [comment]
> sorry for the pile ups, was happy copying rust's trick

And rust thing was a port of D2 solution ;)

**Comment by jinyus** [comment]
The results haven't been updated in a while so I will refresh the entire chart. It will take a few hours to complete

**Pull request merged**
