### PR TITLE
Update app.d

### PR DESCRIPTION
**Pull request by Imperatorn**
I guess the output filename should be _con?

### CODE REVIEW

**Comment by cyrusmsk** [comment]
I also would like to make small changes into this file, before merging.

**Comment by Imperatorn** [comment]
> I also would like to make small changes into this file, before merging.

Sorry, I also forgot to check the output file, did a separate PR. Sorry for the mess

**Comment by cyrusmsk** [comment]
> I also would like to make small changes into this file, before merging.

ok. I've prepared new PR with small adjustments.

**Comment by cyrusmsk** [comment]
Can you remove "result" array from the code - it is doing nothing

**Comment by Imperatorn** [comment]
> Can you remove "result" array from the code - it is doing nothing

Looks like I missed a lot of things today. Will fix

**Pull request closed without merging**
