### PR TITLE
Restore Julia's number type optimization from #171

### PR DESCRIPTION
**Pull request by LilithHafner**
Reverts the removal by @MasonProtter in #207

Also removes trailing whitespace

### CODE REVIEW

**Comment by cyrusmsk** [comment]
Btw what is the logic behind this optimization?
Smaller type will require less memory, but why it should work faster?

**Comment by MasonProtter** [comment]
If you do this, you'll need to change the precompilation workload to make sure each path is hit. 

I’m skeptical that there's any performance advantage though.

**Comment by MasonProtter** [comment]
Main:
```
[| Julia | 406.00 ms  |]
Julia:

        Benchmark 1: julia --project=Related -e "using Related; main()"
        Processing time (w/o IO): 19 milliseconds
        Processing time (w/o IO): 20 milliseconds
        Processing time (w/o IO): 19 milliseconds
        Processing time (w/o IO): 20 milliseconds
        Processing time (w/o IO): 20 milliseconds
        Processing time (w/o IO): 20 milliseconds
        Processing time (w/o IO): 20 milliseconds
        Processing time (w/o IO): 19 milliseconds
        Processing time (w/o IO): 20 milliseconds
        Processing time (w/o IO): 20 milliseconds
        Processing time (w/o IO): 20 milliseconds
        Processing time (w/o IO): 20 milliseconds
        Processing time (w/o IO): 20 milliseconds
          Time (mean ± σ):     558.8 ms ±  10.6 ms    [User: 550.3 ms, System: 365.2 ms]
          Range (min … max):   544.3 ms … 579.9 ms    10 runs
         
Julia:

        Benchmark 1: julia --project=Related -e "using Related; main()"
        Processing time (w/o IO): 249 milliseconds
        Processing time (w/o IO): 249 milliseconds
        Processing time (w/o IO): 257 milliseconds
          Time (mean ± σ):     855.8 ms ±  33.6 ms    [User: 864.5 ms, System: 347.9 ms]
          Range (min … max):   832.1 ms … 879.6 ms    2 runs
         
Julia:

        Benchmark 1: julia --project=Related -e "using Related; main()"
        Processing time (w/o IO): 2188 milliseconds
        Processing time (w/o IO): 2217 milliseconds
        Processing time (w/o IO): 2297 milliseconds
          Time (mean ± σ):      3.037 s ±  0.050 s    [User: 3.008 s, System: 0.371 s]
          Range (min … max):    3.001 s …  3.072 s    2 runs
```
This PR:
```
[| Julia | 552.89 ms  |]
Julia:

        Benchmark 1: julia --project=Related -e "using Related; main()"
        Processing time (w/o IO): 29 milliseconds
        Processing time (w/o IO): 29 milliseconds
        Processing time (w/o IO): 28 milliseconds
        Processing time (w/o IO): 33 milliseconds
        Processing time (w/o IO): 29 milliseconds
        Processing time (w/o IO): 28 milliseconds
        Processing time (w/o IO): 28 milliseconds
        Processing time (w/o IO): 28 milliseconds
        Processing time (w/o IO): 29 milliseconds
        Processing time (w/o IO): 28 milliseconds
        Processing time (w/o IO): 28 milliseconds
        Processing time (w/o IO): 28 milliseconds
        Processing time (w/o IO): 28 milliseconds
          Time (mean ± σ):     572.0 ms ±  25.2 ms    [User: 574.0 ms, System: 351.6 ms]
          Range (min … max):   551.5 ms … 634.0 ms    10 runs
         
Julia:

        Benchmark 1: julia --project=Related -e "using Related; main()"
        Processing time (w/o IO): 334 milliseconds
        Processing time (w/o IO): 354 milliseconds
        Processing time (w/o IO): 349 milliseconds
          Time (mean ± σ):     950.1 ms ±  18.1 ms    [User: 923.2 ms, System: 383.0 ms]
          Range (min … max):   937.3 ms … 962.8 ms    2 runs
         
Julia:

        Benchmark 1: julia --project=Related -e "using Related; main()"
        Processing time (w/o IO): 2999 milliseconds
        Processing time (w/o IO): 2986 milliseconds
        Processing time (w/o IO): 3110 milliseconds
          Time (mean ± σ):      3.848 s ±  0.092 s    [User: 3.802 s, System: 0.397 s]
          Range (min … max):    3.783 s …  3.914 s    2 runs
```

**Comment by jinyus** [comment]
Main:
`Julia | 37.15 ms | 481.67 ms | 4.22 s`

This PR:
```
Julia:

        Benchmark 1: julia --project=Related -e "using Related; main()"
        Processing time (w/o IO): 34 milliseconds
        Processing time (w/o IO): 33 milliseconds
        Processing time (w/o IO): 34 milliseconds
        Processing time (w/o IO): 34 milliseconds
        Processing time (w/o IO): 34 milliseconds
        Processing time (w/o IO): 34 milliseconds
        Processing time (w/o IO): 36 milliseconds
        Processing time (w/o IO): 34 milliseconds
        Processing time (w/o IO): 35 milliseconds
        Processing time (w/o IO): 34 milliseconds
        Processing time (w/o IO): 34 milliseconds
        Processing time (w/o IO): 34 milliseconds
        Processing time (w/o IO): 34 milliseconds
          Time (mean ± σ):      1.038 s ±  0.018 s    [User: 0.911 s, System: 0.231 s]
          Range (min … max):    1.018 s …  1.065 s    10 runs
         
Julia:

        Benchmark 1: julia --project=Related -e "using Related; main()"
        Processing time (w/o IO): 346 milliseconds
        Processing time (w/o IO): 345 milliseconds
        Processing time (w/o IO): 343 milliseconds
          Time (mean ± σ):      1.480 s ±  0.005 s    [User: 1.298 s, System: 0.285 s]
          Range (min … max):    1.476 s …  1.484 s    2 runs
         
Julia:

        Benchmark 1: julia --project=Related -e "using Related; main()"
        Processing time (w/o IO): 2918 milliseconds
        Processing time (w/o IO): 2922 milliseconds
        Processing time (w/o IO): 2916 milliseconds
          Time (mean ± σ):      4.451 s ±  0.010 s    [User: 4.200 s, System: 0.347 s]
          Range (min … max):    4.444 s …  4.458 s    2 runs
```

**Pull request merged**
