### PR TITLE
Update app.d

### PR DESCRIPTION
**Pull request by Imperatorn**
Some formatting and updated algo

### CODE REVIEW

**Comment by Imperatorn** [comment]
On my local machine with latest Go and D, D performs slightly better than Go.

Will be interesting to see if you get the same results.

**Comment by jinyus** [comment]
Faster but not correct:

```
Checking output
Error: Post jf0da9ku is invalid!
expected: 15 shared tag count
actual: 11
```

This means it's not selecting the correct top5

**Comment by Imperatorn** [comment]
Oh, I messed up. Will fix, thanks

**Comment by Imperatorn** [comment]
> Faster but not correct:
> 
> ```
> Checking output
> Error: Post jf0da9ku is invalid!
> expected: 15 shared tag count
> actual: 11
> ```
> 
> This means it's not selecting the correct top5

Fixed the error

**Comment by jinyus** [comment]
~1ms faster

**Pull request merged**
