### PR TITLE
[rust] Reduce number of allocations

### PR DESCRIPTION
**Pull request by cloneable**
* Use `fxhash` crate directly with the HashMap from `std` so we can set an initial capacity.

### CODE REVIEW

**Comment by jinyus** [comment]
Hey, I'm in the process of switch the VM from azure to aws `c7a.xlarge` which is more powerful and modern CPU. This is slower on the new machine.

Main:
```
Rust:

        Processing time (w/o IO): 16.869763ms
        total: 0.02s memory: 12544k
        Processing time (w/o IO): 16.184267ms
        total: 0.03s memory: 12544k
        Processing time (w/o IO): 15.882718ms
        total: 0.03s memory: 12416k
        Processing time (w/o IO): 16.095077ms
        total: 0.03s memory: 12544k
        Processing time (w/o IO): 16.034897ms
        total: 0.03s memory: 12416k
        Processing time (w/o IO): 16.061467ms
        total: 0.02s memory: 12288k
        Processing time (w/o IO): 16.962193ms
        total: 0.02s memory: 12416k
        Processing time (w/o IO): 16.439936ms
        total: 0.02s memory: 12288k
        Processing time (w/o IO): 16.978492ms
        total: 0.02s memory: 12160k
        Processing time (w/o IO): 15.882838ms
        total: 0.02s memory: 12288k

Rust:

        Processing time (w/o IO): 239.925547ms
        total: 0.31s memory: 35660k
        Processing time (w/o IO): 243.774886ms
        total: 0.32s memory: 35536k
        Processing time (w/o IO): 230.044077ms
        total: 0.30s memory: 35536k

Rust:

        Processing time (w/o IO): 2.046692215s
        total: 2.33s memory: 102544k
        Processing time (w/o IO): 2.049446821s
        total: 2.34s memory: 102544k
        Processing time (w/o IO): 2.063887487s
        total: 2.34s memory: 102548k
```

This PR:
```
Rust:

        Processing time (w/o IO): 21.230628ms
        total: 0.03s memory: 12032k
        Processing time (w/o IO): 19.247057ms
        total: 0.03s memory: 12160k
        Processing time (w/o IO): 20.460351ms
        total: 0.04s memory: 12288k
        Processing time (w/o IO): 19.081157ms
        total: 0.03s memory: 12160k
        Processing time (w/o IO): 19.126838ms
        total: 0.03s memory: 11904k
        Processing time (w/o IO): 20.602091ms
        total: 0.03s memory: 12032k
        Processing time (w/o IO): 19.874814ms
        total: 0.03s memory: 11904k
        Processing time (w/o IO): 18.985449ms
        total: 0.03s memory: 12032k
        Processing time (w/o IO): 18.898789ms
        total: 0.03s memory: 12160k
        Processing time (w/o IO): 19.092188ms
        total: 0.03s memory: 12160k

Rust:

        Processing time (w/o IO): 281.861893ms
        total: 0.35s memory: 35072k
        Processing time (w/o IO): 283.530715ms
        total: 0.35s memory: 34944k
        Processing time (w/o IO): 283.143567ms
        total: 0.35s memory: 35072k

Rust:

        Processing time (w/o IO): 2.511316448s
        total: 2.77s memory: 100532k
        Processing time (w/o IO): 2.490994385s
        total: 2.76s memory: 100524k
        Processing time (w/o IO): 2.505934828s
        total: 2.74s memory: 100660k
```

**Comment by cloneable** [comment]
Hey, so I got myself a c7a.xlarge and I'm seeing different values. Can you confirm that what you posted above for "main" is indeed a fresh run from clean main head on c7a.xlarge? With Rust 1.74/1.73 I get ~21ms for 5k for main. With optimizations I get 15.6ms.

**Comment by jinyus** [comment]
Here is a fresh run:
```
Rust:

        Processing time (w/o IO): 16.110144ms
        total: 0.02s memory: 12416k
        Processing time (w/o IO): 16.424593ms
        total: 0.03s memory: 12288k
        Processing time (w/o IO): 16.130734ms
        total: 0.04s memory: 12416k
        Processing time (w/o IO): 16.436733ms
        total: 0.03s memory: 12416k
        Processing time (w/o IO): 16.369473ms
        total: 0.02s memory: 12544k
        Processing time (w/o IO): 16.074224ms
        total: 0.02s memory: 12416k
        Processing time (w/o IO): 16.015375ms
        total: 0.02s memory: 12416k
        Processing time (w/o IO): 16.480684ms
        total: 0.02s memory: 12416k
        Processing time (w/o IO): 18.177838ms
        total: 0.02s memory: 12544k
        Processing time (w/o IO): 17.46669ms
        total: 0.02s memory: 12416k

Rust:

        Processing time (w/o IO): 231.80284ms
        total: 0.29s memory: 35536k
        Processing time (w/o IO): 239.382938ms
        total: 0.30s memory: 35408k
        Processing time (w/o IO): 235.18608ms
        total: 0.30s memory: 35540k

Rust:

        Processing time (w/o IO): 2.088027485s
        total: 2.33s memory: 119164k
        Processing time (w/o IO): 2.057614801s
        total: 2.29s memory: 119164k
        Processing time (w/o IO): 2.038391585s
        total: 2.28s memory: 102684k
```

This is the old run used for the leaderboard:

https://github.com/jinyus/related_post_gen/blob/636cf10a96209ef457da0ede37067a33b7fa62c4/raw_results.md?plain=1#L55

**Comment by jinyus** [comment]
```
> uname -a
Linux ip-172-xxxx-aws #12~22.04.1-Ubuntu SMP Thu Sep  7 14:01:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

> cat /proc/cpuinfo | grep model
model           : 17
model name      : AMD EPYC 9R14
model           : 17
model name      : AMD EPYC 9R14
model           : 17
model name      : AMD EPYC 9R14
model           : 17
model name      : AMD EPYC 9R14

> sudo docker run -it --rm databench bash
[root@51460ba4e95b app]# rustc --version
rustc 1.74.0 (79e9716c9 2023-11-13)
```

**Comment by jinyus** [comment]
@cloneable Let's see your `rustc verison`

I would like to see your numbers in docker. Here is a single command to install docker and run the test:

```
sudo apt update &&
    sudo apt install -y apt-transport-https ca-certificates curl software-properties-common &&
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg &&
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list >/dev/null &&
    sudo apt update &&
    apt-cache policy docker-ce &&
    sudo apt install -y docker-ce &&
    sudo docker pull ghcr.io/jinyus/databench:latest &&
    sudo docker tag ghcr.io/jinyus/databench databench &&
    sudo docker run -it --rm -e TEST_NAME=rust databench
```

**Comment by cloneable** [comment]
Thank you! That works. Now I get similar numbers.

**Pull request closed without merging**
