### PR TITLE
Performance Improvement (Julia)

### PR DESCRIPTION
**Pull request by algunion**
Some minor changes - performance improvement related.

### CODE REVIEW

**Comment by algunion** [comment]
Let me check the correctness before checking this.

**Comment by jinyus** [comment]
This version is not correct, you need to modify the run.sh to check `related_posts_julia.json`. It's currently checking `related_posts_julia_v1.json`

**Comment by algunion** [comment]
> This version is not correct, you need to modify the run.sh to check `related_posts_julia.json`. It's currently checking `related_posts_julia_v1.json`

Yes - I figured that out right away.

**Comment by algunion** [comment]
@jinyus - please check now.

**Comment by jinyus** [comment]
I'm seeing 1-2ms speed up

**Comment by algunion** [comment]
> I'm seeing 1-2ms speed up

I'll need to go over it in more depth later - I'll leave it in this state for now. 

The goal was to bring the stats closer to Rust (because values > 0.5 seconds were pretty weird for Julia).

Also - you did an excellent job with a real-world benchmark (as opposed to useless micro-benchmarks).

**Comment by jinyus** [comment]
Thanks, this bench mark was formed from a real world problem. 

I was using golang for a similar problem and it was too slow so I tried rust and it was even slower. That's when I posted my findings to the rust community and I thought this be a great test for other languages

**Pull request merged**
