### PR TITLE
Try use StaticArrays.jl again for Julia

### PR DESCRIPTION
**Pull request by Moelf**
Following the latest discussion in:
- https://github.com/jinyus/related_post_gen/issues/194#issuecomment-1777172218

@algunion @LilithHafner

### CODE REVIEW

**Comment by jinyus** [comment]
Main:
`Julia | 30.38 ms | 481.33 ms | 4.23 s`

This PR:
```
Julia:

        Benchmark 1: julia --project=Related -e "using Related; main()"
        Processing time (w/o IO): 30 milliseconds
        Processing time (w/o IO): 30 milliseconds
        Processing time (w/o IO): 30 milliseconds
        Processing time (w/o IO): 30 milliseconds
        Processing time (w/o IO): 30 milliseconds
        Processing time (w/o IO): 30 milliseconds
        Processing time (w/o IO): 30 milliseconds
        Processing time (w/o IO): 29 milliseconds
        Processing time (w/o IO): 30 milliseconds
        Processing time (w/o IO): 30 milliseconds
        Processing time (w/o IO): 30 milliseconds
        Processing time (w/o IO): 30 milliseconds
        Processing time (w/o IO): 30 milliseconds
          Time (mean ± σ):     990.7 ms ±  12.9 ms    [User: 883.0 ms, System: 211.2 ms]
          Range (min … max):   973.7 ms … 1012.2 ms    10 runs
         
Julia:

        Benchmark 1: julia --project=Related -e "using Related; main()"
        Processing time (w/o IO): 367 milliseconds
        Processing time (w/o IO): 389 milliseconds
        Processing time (w/o IO): 366 milliseconds
          Time (mean ± σ):      1.487 s ±  0.008 s    [User: 1.334 s, System: 0.255 s]
          Range (min … max):    1.481 s …  1.493 s    2 runs
         
Julia:

        Benchmark 1: julia --project=Related -e "using Related; main()"
        Processing time (w/o IO): 3157 milliseconds
        Processing time (w/o IO): 3158 milliseconds
        Processing time (w/o IO): 3156 milliseconds
          Time (mean ± σ):      4.585 s ±  0.013 s    [User: 4.353 s, System: 0.327 s]
          Range (min … max):    4.576 s …  4.594 s    2 runs
         
```

**Comment by Moelf** [comment]
```
> math '30+389+3158'
3577
```

would rought put Julia somewhere around 5th? not bad I guess

**Comment by algunion** [comment]
> ```
> > math '30+389+3158'
> 3577
> ```
> 
> would roughly put Julia somewhere around 5th? not bad I guess

@Moelf , I am not sure this is optimal.

The _original_ StaticArrays implementation constantly achieved around 23ms for 5K posts (which is actually the value of first place right now - which is Zig).

37.15 ms is quite departing from that result (but I cannot say why - I just took a peek at the code).

I don't have too much time now - but if you have and are willing, you might try to reconcile the past [top result from here](https://github.com/algunion/related_post_gen/blob/rem-btime/julia/related.jl) with the current precompilation setup.

**Comment by Moelf** [comment]
I don't want to add the dynamic dispatch to different type length, because other implementations don't do that I believe

**Comment by Tortar** [comment]
Strangely it seems to me that the Julia version didn't even improve after merging this, the sum of the times is still nearly 5 seconds

**Pull request merged**
