### PR TITLE
C# compile options

### PR DESCRIPTION
**Pull request by zigzag312**
Some nice gains from these compile options

### CODE REVIEW

**Comment by jinyus** [comment]
Quite a bit slower for me (linux):

old:

```
Benchmark 1: ./bin/release/net7.0/publish/related
Processing time (w/o IO): 29.0879ms
Processing time (w/o IO): 29.1496ms
Processing time (w/o IO): 29.9573ms
Processing time (w/o IO): 28.801ms
Processing time (w/o IO): 29.3971ms
Processing time (w/o IO): 29.1676ms
Processing time (w/o IO): 29.2384ms
  Time (mean ± σ):      71.1 ms ±   2.7 ms    [User: 59.8 ms, System: 20.1 ms]
  Range (min … max):    67.3 ms …  74.6 ms    5 runs
```

new:

```
Benchmark 1: ./bin/release/net7.0/publish/related
Processing time (w/o IO): 43.7973ms
Processing time (w/o IO): 42.1617ms
Processing time (w/o IO): 42.7891ms
Processing time (w/o IO): 42.2372ms
Processing time (w/o IO): 41.6079ms
Processing time (w/o IO): 41.9937ms
Processing time (w/o IO): 41.7314ms
Processing time (w/o IO): 42.1395ms
Processing time (w/o IO): 42.2138ms
Processing time (w/o IO): 41.9366ms
Processing time (w/o IO): 44.2133ms
Processing time (w/o IO): 42.9915ms
Processing time (w/o IO): 42.0461ms
Processing time (w/o IO): 42.3655ms
Processing time (w/o IO): 42.4067ms
  Time (mean ± σ):      83.4 ms ±   1.8 ms    [User: 66.3 ms, System: 24.2 ms]
  Range (min … max):    81.5 ms …  86.7 ms    10 runs
```

**Comment by delneg** [comment]
It's against the rules to use 
    ```<IlcInstructionSet>x86-x64-v3</IlcInstructionSet>```
because it ties to x86_64 architecture (and moreover, specific CPU's)
```No Specific hardware targeting``` - the rules

**Comment by zigzag312** [comment]
@jinyus Interesting. For me, on Windows performance improved (total time) when I enabled  `<InvariantGlobalization>true</InvariantGlobalization>`. 

`<StripSymbols>true</StripSymbols>` strips debugging symbols from the produced executable into a separate file. In NET 7 debugging symbols on Linux are placed into the produced executable by default, but in NET 8 they are stripped by default. No change on Windows.

Ilc* ones didn't produce meaningful change on my machine, they just seemed like they could help.

Can you test just `<InvariantGlobalization>true</InvariantGlobalization>`? And maybe optionally `<StripSymbols>true</StripSymbols>`?

**Comment by jinyus** [comment]
Not much difference.

old:

```
Benchmark 1: ./bin/release/net7.0/publish/related
Processing time (w/o IO): 27.4974ms
Processing time (w/o IO): 28.0569ms
Processing time (w/o IO): 29.5755ms
Processing time (w/o IO): 27.9039ms
Processing time (w/o IO): 28.7221ms
Processing time (w/o IO): 28.7305ms
Processing time (w/o IO): 28.6407ms
  Time (mean ± σ):      70.2 ms ±   1.9 ms    [User: 54.4 ms, System: 24.6 ms]
```

new:

```
Benchmark 1: ./bin/release/net7.0/publish/related
Processing time (w/o IO): 28.3492ms
Processing time (w/o IO): 27.4525ms
Processing time (w/o IO): 28.7766ms
Processing time (w/o IO): 28.7748ms
Processing time (w/o IO): 27.6586ms
Processing time (w/o IO): 29.4482ms
Processing time (w/o IO): 28.6628ms
  Time (mean ± σ):      72.9 ms ±   0.6 ms    [User: 55.3 ms, System: 27.0 ms]
```

**Comment by Jure-BB** [comment]
No meaningful difference. Thanks for testing on Linux. 

I thought I could get C# close to Go's performance, but I'm out of ideas.

**Comment by zigzag312** [comment]
No meaningful difference. Thanks for testing on Linux.

I thought I could get C# close to Go's performance, but I'm out of ideas.

**Comment by jinyus** [comment]
Go performance is very surprising. DIdn't expect it to be trading blows with rust and zig.

**Comment by zigzag312** [comment]
Java (GraalVM) is also surprising. Really very good .

**Pull request closed without merging**
