### PR TITLE
common lisp: change post representation data structure

### PR DESCRIPTION
**Pull request by leetwinski**
update post representation to struct
~20% speedup on my machine

### CODE REVIEW

**Comment by jinyus** [comment]
Main:
```
| Common Lisp (SBCL) | 214.00 ms | 1.18 s | 8.99 s |
```

This PR:
```yaml
Common Lisp (SBCL):

        Processing time (w/o IO): 0.12 s
        Processing time total: 0.22 s
        total: 0.22s memory: 122240k
        Processing time (w/o IO): 0.12 s
        Processing time total: 0.22 s
        total: 0.22s memory: 122240k
        Processing time (w/o IO): 0.12 s
        Processing time total: 0.22 s
        total: 0.22s memory: 122112k
        Processing time (w/o IO): 0.12 s
        Processing time total: 0.22 s
        total: 0.22s memory: 122368k
        Processing time (w/o IO): 0.12 s
        Processing time total: 0.22 s
        total: 0.22s memory: 122368k
        Processing time (w/o IO): 0.12 s
        Processing time total: 0.21 s
        total: 0.22s memory: 122112k
        Processing time (w/o IO): 0.12 s
        Processing time total: 0.22 s
        total: 0.22s memory: 122368k
        Processing time (w/o IO): 0.12 s
        Processing time total: 0.22 s
        total: 0.22s memory: 122240k
        Processing time (w/o IO): 0.12 s
        Processing time total: 0.22 s
        total: 0.22s memory: 122240k
        Processing time (w/o IO): 0.12 s
        Processing time total: 0.22 s
        total: 0.22s memory: 122240k

Common Lisp (SBCL):

        Processing time (w/o IO): 0.97 s
        Processing time total: 1.36 s
        total: 1.37s memory: 152856k
        Processing time (w/o IO): 0.98 s
        Processing time total: 1.37 s
        total: 1.38s memory: 152600k

Common Lisp (SBCL):

        Processing time (w/o IO): 8.07 s
        Processing time total: 9.40 s
        total: 9.42s memory: 353244k
        Processing time (w/o IO): 8.09 s
        Processing time total: 9.44 s
        total: 9.46s memory: 353240k
```

**Comment by leetwinski** [comment]
> ps: You might want to remove the total processing time from the program as it's reported by the time command.
will do.

btw, how do you calculate the result in for the table? is it (total + calculation) / 2?

**Comment by jinyus** [comment]
I just add up the individual rounds. Total isn't take into consideration because it includes json processing.

**Comment by leetwinski** [comment]
hm. 
`Common Lisp (SBCL)	169.50 ms	1.17 s	8.75 s	10.09 s`
in the table, while above in this pr comments: 

        Processing time (w/o IO): 0.12 s
        Processing time total: 0.22 s

        Processing time (w/o IO): 0.98 s
        Processing time total: 1.37 s

        Processing time (w/o IO): 8.09 s
        Processing time total: 9.44 s

so that really looks like avgs of each pair

**Comment by leetwinski** [comment]
anyways, i will remove the total time line from tte output. just a minute

**Comment by jinyus** [comment]
> hm. `Common Lisp (SBCL) 169.50 ms 1.17 s 8.75 s 10.09 s` in the table, while above in this pr comments:
> 
> ```
>     Processing time (w/o IO): 0.12 s
>     Processing time total: 0.22 s
> 
>     Processing time (w/o IO): 0.98 s
>     Processing time total: 1.37 s
> 
>     Processing time (w/o IO): 8.09 s
>     Processing time total: 9.44 s
> ```
> 
> so that really looks like avgs of each pair

You're right, I avg each round then add the averages

**Comment by leetwinski** [comment]
so that must mean that removing extra output line (`"Processing time total: ~2$ s~%"`) from the code would improve that? )

**Comment by jinyus** [comment]
omg, I see what you're saying now. The regex used to extract the scores is doesn't check for the `(w/o IO)` part so it's counting total for lisp. Sorry about that.

https://github.com/jinyus/related_post_gen/blob/a32fb8cd9dea5a5df4ebb8828d0567cf71dab2fc/extract_results.dart#L7

**Comment by jinyus** [comment]
Total oversight on my part. It's fixed now:

https://github.com/jinyus/related_post_gen/blob/c55ff43d4c6b8ce6cdd2f41613586bab824125d5/readme.md?plain=1#L91

**Comment by leetwinski** [comment]
thank you so much!

i removed that extra line in this pr, 
https://github.com/jinyus/related_post_gen/pull/504

**Pull request merged**
