### PR TITLE
[Nim] clang again

### PR DESCRIPTION
**Pull request by inv2004**
@jinyus 
I was a bit confused that you fixed the clang problem and merged `gcc_again` at the same time :)

Can I ask you to check the PR before merge. + If you can show `clang --version` we added into `buildopt` if possible - to be extra-sure.

Thank you,

### CODE REVIEW

**Comment by jinyus** [comment]
I merged because gcc is faster https://github.com/jinyus/related_post_gen/pull/345#issuecomment-1772666659.

This PR:
```
gcc (GCC) 13.2.1 20230801                                                                                                                                                                                                                      
clang version 16.0.6                                                                                                                                                                                                                           
  Verifying dependencies for related@0.1.0                                                                                                                                                                                                     
     Info:  Dependency on jsony@any version already satisfied                                                                                                                                                                                  
  Verifying dependencies for jsony@1.1.5
     Info:  Dependency on xxhash@any version already satisfied
  Verifying dependencies for xxhash@0.9.0
   Building related/related using c backend
Build with profileGen
Gen stat 1/10
Gen stat 2/10
Gen stat 3/10
Gen stat 4/10
Gen stat 5/10
Gen stat 6/10
Gen stat 7/10
Gen stat 8/10
Gen stat 9/10
Gen stat 10/10
  Verifying dependencies for related@0.1.0
     Info:  Dependency on jsony@any version already satisfied
  Verifying dependencies for jsony@1.1.5
     Info:  Dependency on xxhash@any version already satisfied
  Verifying dependencies for xxhash@0.9.0
   Building related/related using c backend
Build with profileUse
Nim:

        Benchmark 1: ./related
        Processing time (w/o IO): 35.851ms
        Processing time (w/o IO): 35.643ms
        Processing time (w/o IO): 35.735ms
        Processing time (w/o IO): 35.712ms
        Processing time (w/o IO): 35.88ms
        Processing time (w/o IO): 35.781ms
        Processing time (w/o IO): 35.543ms
        Processing time (w/o IO): 35.488ms
        Processing time (w/o IO): 35.489ms
        Processing time (w/o IO): 35.672ms
        Processing time (w/o IO): 35.534ms
        Processing time (w/o IO): 35.66ms
        Processing time (w/o IO): 35.501ms
          Time (mean ± σ):      61.3 ms ±   0.6 ms    [User: 50.0 ms, System: 11.3 ms]
          Range (min … max):    60.6 ms …  62.5 ms    10 runs
         
Checking output
Success: related_posts_nim.json is valid!

Nim:

        Benchmark 1: ./related
        Processing time (w/o IO): 521.066ms
        Processing time (w/o IO): 529.878ms
        Processing time (w/o IO): 521.265ms
          Time (mean ± σ):     626.6 ms ±   7.0 ms    [User: 578.9 ms, System: 47.6 ms]
          Range (min … max):   621.7 ms … 631.6 ms    2 runs
         
Nim:

        Benchmark 1: ./related
        Processing time (w/o IO): 4597.794ms
        Processing time (w/o IO): 4587.004ms
        Processing time (w/o IO): 4596.289ms
          Time (mean ± σ):      4.950 s ±  0.001 s    [User: 4.838 s, System: 0.107 s]
          Range (min … max):    4.949 s …  4.951 s    2 runs

```

**Comment by inv2004** [comment]
Thank you.

Lets not merge, but to investigate. The numbers are really bad, which does not match local tests

**Comment by inv2004** [comment]
@jinyus 
Can I ask to retest again with the last change? Because the only idea I have - the stats does not always work (confirmed locally). Maybe for VM it is a bit worse

**Comment by jinyus** [comment]
Better:

```
Nim:

        Benchmark 1: ./related
        Processing time (w/o IO): 30.514ms
        Processing time (w/o IO): 30.217ms
        Processing time (w/o IO): 30.214ms
        Processing time (w/o IO): 30.091ms
        Processing time (w/o IO): 30.443ms
        Processing time (w/o IO): 30.369ms
        Processing time (w/o IO): 30.237ms
        Processing time (w/o IO): 30.206ms
        Processing time (w/o IO): 30.371ms
        Processing time (w/o IO): 30.294ms
        Processing time (w/o IO): 30.565ms
        Processing time (w/o IO): 30.27ms
        Processing time (w/o IO): 30.322ms
          Time (mean ± σ):      54.8 ms ±   0.4 ms    [User: 44.9 ms, System: 9.9 ms]
          Range (min … max):    54.5 ms …  55.6 ms    10 runs
         
Nim:

        Benchmark 1: ./related
        Processing time (w/o IO): 434.77ms
        Processing time (w/o IO): 437.037ms
        Processing time (w/o IO): 435.437ms
          Time (mean ± σ):     534.6 ms ±   1.1 ms    [User: 498.9 ms, System: 35.7 ms]
          Range (min … max):   533.8 ms … 535.4 ms    2 runs
         
Nim:

        Benchmark 1: ./related
        Processing time (w/o IO): 3838.045ms
        Processing time (w/o IO): 3836.086ms
        Processing time (w/o IO): 3838.397ms
          Time (mean ± σ):      4.187 s ±  0.007 s    [User: 4.057 s, System: 0.121 s]
          Range (min … max):    4.182 s …  4.192 s    2 runs
```

**Comment by inv2004** [comment]
@jinyus 
Do I understand correct that gcc is still better? It us still strange, I still think something is not right with clang at the step. But lets keep gcc for now

**Comment by jinyus** [comment]
Yea, gcc is still faster https://github.com/jinyus/related_post_gen/pull/345#issuecomment-1772666659
Do you want to keep this open?

**Comment by inv2004** [comment]
@jinyus
I am sorry for the flood of question.

But could you please run the change I just added. I think that it is the last would be good to cover

Thank you,

**Comment by jinyus** [comment]
```
Nim:

        Benchmark 1: ./related
        Processing time (w/o IO): 48.664ms
        Processing time (w/o IO): 48.404ms
        Processing time (w/o IO): 48.413ms
        Processing time (w/o IO): 48.341ms
        Processing time (w/o IO): 48.354ms
        Processing time (w/o IO): 48.375ms
        Processing time (w/o IO): 48.477ms
        Processing time (w/o IO): 48.458ms
        Processing time (w/o IO): 48.467ms
        Processing time (w/o IO): 48.525ms
        Processing time (w/o IO): 48.474ms
        Processing time (w/o IO): 48.426ms
        Processing time (w/o IO): 49.948ms
          Time (mean ± σ):      75.9 ms ±   0.5 ms    [User: 63.8 ms, System: 12.1 ms]
          Range (min … max):    75.3 ms …  76.9 ms    10 runs
         
Nim:

        Benchmark 1: ./related
        Processing time (w/o IO): 725.4400000000001ms
        Processing time (w/o IO): 725.5069999999999ms
        Processing time (w/o IO): 726.427ms
          Time (mean ± σ):     827.6 ms ±   0.4 ms    [User: 790.0 ms, System: 37.4 ms]
          Range (min … max):   827.3 ms … 827.8 ms    2 runs
         
Nim:

        Benchmark 1: ./related
        Processing time (w/o IO): 6415.608ms
        Processing time (w/o IO): 6421.586ms
        Processing time (w/o IO): 6420.489ms
          Time (mean ± σ):      6.775 s ±  0.005 s    [User: 6.647 s, System: 0.117 s]
          Range (min … max):    6.771 s …  6.778 s    2 runs
```

**Comment by inv2004** [comment]
@jinyus Thank you. Lets keep it open

My conclusion - clang is still broken because it was never the same locally. Probably it is some mix of fresh clang binary and old llvm lib from swift, but it is just an idea

**Comment by inv2004** [comment]
@jinyus 
Not 100% sure in the fix. It is possible that clang bin is linked with old .so which is ldpath or ldcache or smth like that

But it is just attempt to find why the numbers are wrong with clang

**Pull request closed without merging**
