### PR TITLE
Update Inko for 0.17.0

### PR DESCRIPTION
**Pull request by yorickpeterse**
**NOTE:** Inko 0.17.0 isn't released yet, I've simply set up this PR ahead of time so I won't forget about it later :smiley: 

This updates the Inko implementation for the 0.17.0 release.

### CODE REVIEW

**Comment by yorickpeterse** [comment]
In the upcoming 0.17.0 release, Inko's compiler is able to inline methods across compilation units. When combining this with `inko build --opt=aggressive`, there's an 8.5x increase in performance compared to `inko build --opt=none`, with the 5k run going from 2.88 seconds to 0.33 seconds. That's still about 10x slower compared to e.g. Go, but we're getting there :smiley:

**Comment by yorickpeterse** [comment]
To illustrate the impact of the `--opt` option better:

| Level              | Processing time (w/o IO)
|:-------------------|:----------------
| `--opt=none`       | 2878 ms
| `--opt=balanced`   | 764 ms
| `--opt=aggressive` | 332 ms

**Comment by yorickpeterse** [comment]
@jinyus Inko 0.17.0 [is released](https://inko-lang.org/news/inko-0-17-0-released/), so this PR is ready for review.

**Comment by jinyus** [comment]
I'm seeing a 14x speed up.

Main:
```sh
| Inko| 6.29 s | 98.05 s | 875.39 s | 979.73 s |
```
This PR:
```sh
| Inko| 439 ms | 6.83 s | 61.27 s | 68.54 s |
```

**Pull request merged**
