### PR TITLE
Zig contribution and Benchmarking on Github actions runner

### PR DESCRIPTION
**Pull request by akhildevelops**
This Pr provides contribution based on Zig language.

It also has a githubactions workflow file that generates benchmarks on the fly for every PR to main.

### CODE REVIEW

**Comment by jinyus** [comment]
Hey, thanks for the PR, Zig has very slow I/O on my machine (5s in total, 80ms on processing). Is that normal?

**Comment by akhildevelops** [comment]
It shudn't take 5s.

**Comment by jinyus** [comment]
These are the results from the github workflow:

Zig:
```
    Benchmark 1: ./main
    Processing time (w/o IO): 176ms
    Processing time (w/o IO): 176ms
    Processing time (w/o IO): 176ms
    Processing time (w/o IO): 176ms
    Processing time (w/o IO): 176ms
    Processing time (w/o IO): 176ms
    Processing time (w/o IO): 176ms
    Processing time (w/o IO): 176ms
    Processing time (w/o IO): 176ms
    Processing time (w/o IO): 176ms
    Processing time (w/o IO): 176ms
    Processing time (w/o IO): 176ms
    Processing time (w/o IO): 176ms

    Time (mean ± σ):      2.205 s ±  0.008 s    [User: 0.719 s, System: 1.484 s]
    Range (min … max):    2.198 s …  2.228 s    10 runs
```

**Comment by akhildevelops** [comment]
> These are the results from the github workflow:
> 
> Zig:
> 
> ```
>     Benchmark 1: ./main
>     Processing time (w/o IO): 176ms
>     Processing time (w/o IO): 176ms
>     Processing time (w/o IO): 176ms
>     Processing time (w/o IO): 176ms
>     Processing time (w/o IO): 176ms
>     Processing time (w/o IO): 176ms
>     Processing time (w/o IO): 176ms
>     Processing time (w/o IO): 176ms
>     Processing time (w/o IO): 176ms
>     Processing time (w/o IO): 176ms
>     Processing time (w/o IO): 176ms
>     Processing time (w/o IO): 176ms
>     Processing time (w/o IO): 176ms
> 
>     Time (mean ± σ):      2.205 s ±  0.008 s    [User: 0.719 s, System: 1.484 s]
>     Range (min … max):    2.198 s …  2.228 s    10 runs
> ```

This is fine generally total time is 10x compared to w/o IO. My system also gives me similar multiplier value.
``` shell
~ $ ./run.sh zig
Running Zig
Benchmark 1: ./main
Processing time (w/o IO): 133ms
Processing time (w/o IO): 133ms
Processing time (w/o IO): 131ms
Processing time (w/o IO): 133ms
Processing time (w/o IO): 131ms
Processing time (w/o IO): 135ms
Processing time (w/o IO): 131ms
Processing time (w/o IO): 130ms
Processing time (w/o IO): 132ms
Processing time (w/o IO): 132ms
Processing time (w/o IO): 137ms
Processing time (w/o IO): 140ms
Processing time (w/o IO): 135ms
  Time (mean ± σ):      1.065 s ±  0.025 s    [User: 0.229 s, System: 0.834 s]
  Range (min … max):    1.031 s …  1.119 s    10 runs
 
Checking output
Output file: related_posts_zig.json is valid!
```

**Comment by jinyus** [comment]
Alright, looks like it might be a bug with my processor/os.

```
Processing time (w/o IO): 80ms
Processing time (w/o IO): 84ms
Processing time (w/o IO): 90ms
Processing time (w/o IO): 90ms
Processing time (w/o IO): 89ms
  Time (mean ± σ):      6.134 s ±  0.190 s    [User: 0.251 s, System: 5.880 s]
  Range (min … max):    5.813 s …  6.488 s    10 runs
```

**Comment by akhildevelops** [comment]
System time is very high i.e, 5secs. This is the time spent by app in sys calls i.e, memory allocation, file reading etc..,. How about other lang implementation system times ?  Are they also high as zig i.e, 20x compared to user time ?

**Comment by jinyus** [comment]
I just merged a fix : #31 

```
Running Zig
Benchmark 1: ./main
Processing time (w/o IO): 80ms
Processing time (w/o IO): 80ms
Processing time (w/o IO): 82ms
Processing time (w/o IO): 80ms
Processing time (w/o IO): 81ms
Processing time (w/o IO): 81ms
Processing time (w/o IO): 82ms
Processing time (w/o IO): 81ms
Processing time (w/o IO): 79ms
Processing time (w/o IO): 81ms
Processing time (w/o IO): 80ms
Processing time (w/o IO): 82ms
Processing time (w/o IO): 82ms
  Time (mean ± σ):     111.7 ms ±   1.7 ms    [User: 99.2 ms, System: 12.4 ms]
  Range (min … max):   109.2 ms … 113.4 ms    10 runs
```

**Comment by akhildevelops** [comment]
Are these from ur local system ?

**Comment by jinyus** [comment]
Yes, the workflow also go a boost: https://github.com/jinyus/related_post_gen#updated-results-from-github-workflow-raw-data

**Comment by akhildevelops** [comment]
I'm working on automatic publishing of benchmarking results (from GitHub runner) in Readme. I'll give a separate PR once it's done.

**Comment by jinyus** [comment]
I wrote a crystal script to extract the results from the workflow log:
https://github.com/jinyus/related_post_gen/blob/main/extract/extract.cr

it prints the new table for the readme and update the raw_results.md file. I should probably rewrite it in python/dart so it can be ran without compiling.

**Comment by akhildevelops** [comment]
Cool, I can direct my efforts on optimizing zig.

**Pull request merged**
