### PR TITLE
[cpp con] add cpp concurrent

### PR DESCRIPTION
**Pull request by kaiwu**
first cpp concurrent version

### CODE REVIEW

**Comment by cyrusmsk** [comment]
this looks like a "specific adjustment" :)
`char padding[2 * CACHE_LINE_SIZE - 88];`

**Comment by kaiwu** [comment]
it's not, cpp needs to manually adjust struct size to be multiple of cache line size for concurrent processing, it is to avoid false sharing

btw please use clang++ for concurrent

**Comment by cyrusmsk** [comment]
C++ code currently is not assigning top5 posts into resulted array (relatedPosts). Please check @jinyus

**Comment by jinyus** [comment]
`relatedPost.related[upperBound + 1] = &posts[j];`

seems like an optimization.

@cyrusmsk

**Comment by cyrusmsk** [comment]
Oh it is using references. I haven’t noticed that. Thnx

**Comment by cloneable** [comment]
fyi, this is unsafe: `posts[j]`

**Pull request merged**
