### PR TITLE
Update app.d

### PR DESCRIPTION
**Pull request by Imperatorn**
Minor performance tweak

### CODE REVIEW

**Comment by Imperatorn** [comment]
Note, this is not using size_t or ulong, but uint.

On my system, this gains about 8%

**Comment by cyrusmsk** [comment]
I've tried the similar PR before, but to int, instead of uint. And we had a regression in speed https://github.com/jinyus/related_post_gen/pull/269
And on local system I also can see improvement with this change.

Dear @jinyus, could you please check performance one more time with uint before merging?

**Comment by jinyus** [comment]
Main branch:
```
24.87 ms
317.38 ms
2.71 s
```

This PR:
```
D:

        Benchmark 1: ./related
        Processing time (w/o IO): 33.058ms
        Processing time (w/o IO): 33.007ms
        Processing time (w/o IO): 32.991ms
        Processing time (w/o IO): 33.054ms
        Processing time (w/o IO): 32.5ms
        Processing time (w/o IO): 32.843ms
        Processing time (w/o IO): 33.035ms
        Processing time (w/o IO): 33ms
        Processing time (w/o IO): 32.982ms
        Processing time (w/o IO): 32.902ms
        Processing time (w/o IO): 33.14ms
        Processing time (w/o IO): 33.024ms
        Processing time (w/o IO): 32.53ms
          Time (mean ± σ):     114.8 ms ±   0.8 ms    [User: 104.0 ms, System: 12.0 ms]
          Range (min … max):   113.7 ms … 116.3 ms    10 runs
         
D:

        Benchmark 1: ./related
        Processing time (w/o IO): 443.778ms
        Processing time (w/o IO): 443.212ms
        Processing time (w/o IO): 443.22ms
          Time (mean ± σ):     745.5 ms ±   1.7 ms    [User: 718.2 ms, System: 31.5 ms]
          Range (min … max):   744.3 ms … 746.7 ms    2 runs
         
D:

        Benchmark 1: ./related
        Processing time (w/o IO): 3829.38ms
        Processing time (w/o IO): 3828.65ms
        Processing time (w/o IO): 3834.43ms
          Time (mean ± σ):      4.792 s ±  0.011 s    [User: 4.675 s, System: 0.123 s]
          Range (min … max):    4.785 s …  4.799 s    2 runs

```

**Comment by jinyus** [comment]
Fresh run on main:
```
D:

        Benchmark 1: ./related
        Processing time (w/o IO): 25.426ms
        Processing time (w/o IO): 24.884ms
        Processing time (w/o IO): 24.711ms
        Processing time (w/o IO): 24.354ms
        Processing time (w/o IO): 25.259ms
        Processing time (w/o IO): 24.784ms
        Processing time (w/o IO): 24.87ms
        Processing time (w/o IO): 24.132ms
        Processing time (w/o IO): 25.003ms
        Processing time (w/o IO): 25.197ms
        Processing time (w/o IO): 24.683ms
        Processing time (w/o IO): 24.897ms
        Processing time (w/o IO): 24.693ms
          Time (mean ± σ):     105.0 ms ±   1.3 ms    [User: 97.1 ms, System: 9.3 ms]
          Range (min … max):   103.5 ms … 108.4 ms    10 runs
         
D:

        Benchmark 1: ./related
        Processing time (w/o IO): 316.677ms
        Processing time (w/o IO): 316.934ms
        Processing time (w/o IO): 315.443ms
          Time (mean ± σ):     611.4 ms ±   2.2 ms    [User: 588.7 ms, System: 27.2 ms]
          Range (min … max):   609.9 ms … 613.0 ms    2 runs
         
D:

        Benchmark 1: ./related
        Processing time (w/o IO): 2701.67ms
        Processing time (w/o IO): 2707.95ms
        Processing time (w/o IO): 2706.85ms
          Time (mean ± σ):      3.648 s ±  0.017 s    [User: 3.547 s, System: 0.105 s]
          Range (min … max):    3.636 s …  3.660 s    2 runs      
```

**Comment by Imperatorn** [comment]
Ok, weird. Thanks for testing :)

**Pull request closed without merging**
