### PR TITLE
[cpp] use clang++

### PR DESCRIPTION
**Pull request by kaiwu**

### CODE REVIEW

**Comment by jinyus** [comment]
This is ~1ms slower for me

**Comment by kaiwu** [comment]
i see, somehow it's 10ms faster in my case ... which is strange. no need to merge for now, let me check

**Comment by kaiwu** [comment]
arch linux 

```
$ clang++ --version
clang version 16.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

$ g++ --version
g++ (GCC) 13.2.1 20230801
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by jinyus** [comment]
I have the same versions on arch too. Just double checked and they are not equal for me. The VM is currently running the benchmark so I will check the scores on there when it's done.

```
g++:


Benchmark 1: ./main
Processing time (w/o IO): 15 ms
Processing time (w/o IO): 15 ms
Processing time (w/o IO): 15 ms
Processing time (w/o IO): 15 ms
Processing time (w/o IO): 15 ms
Processing time (w/o IO): 15 ms
Processing time (w/o IO): 15 ms
Processing time (w/o IO): 15 ms
Processing time (w/o IO): 15 ms
Processing time (w/o IO): 15 ms
Processing time (w/o IO): 15 ms
Processing time (w/o IO): 15 ms
Processing time (w/o IO): 15 ms
  Time (mean ± σ):     179.2 ms ±   2.0 ms    [User: 142.6 ms, System: 36.5 ms]
  Range (min … max):   175.7 ms … 182.2 ms    10 runs
 

clang++:

Benchmark 1: ./main
Processing time (w/o IO): 15 ms
Processing time (w/o IO): 15 ms
Processing time (w/o IO): 15 ms
Processing time (w/o IO): 15 ms
Processing time (w/o IO): 15 ms
Processing time (w/o IO): 15 ms
Processing time (w/o IO): 15 ms
Processing time (w/o IO): 15 ms
Processing time (w/o IO): 15 ms
Processing time (w/o IO): 15 ms
Processing time (w/o IO): 15 ms
Processing time (w/o IO): 15 ms
Processing time (w/o IO): 15 ms
  Time (mean ± σ):     186.9 ms ±   2.4 ms    [User: 154.6 ms, System: 32.2 ms]
  Range (min … max):   184.2 ms … 191.1 ms    10 runs
```

**Pull request closed without merging**
