### PR TITLE
[Nim Con] improve performance

### PR DESCRIPTION
**Pull request by michaelsbradleyjr**
Here's a PR with ***only*** the `[Nim Con]` commits, i.e. affecting `nim_con` only, in case there's a hangup about the changes in `nim/` on `main` vs. `nim_rev` branches.

Will post fresh numbers from my Azure VM below. For `nim_con`, `nim_rev` consistently outperforms `main`, especially big differences for 20k and 60k runs.

### CODE REVIEW

**Comment by michaelsbradleyjr** [comment]
*WITHOUT* PGO
**Multi Threaded**
`nim_con` on `nim_rev` branch
```
(related) michael@azure1:~/repos/related_post_gen$ ./nim_con.sh 
  main
* nim_con_rev
...
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 19.249ms
	Processing time (w/o IO): 19.071ms
	Processing time (w/o IO): 19.332ms
	Processing time (w/o IO): 19.68ms
	Processing time (w/o IO): 19.196ms
	Processing time (w/o IO): 19.294ms
	Processing time (w/o IO): 19.353ms
	Processing time (w/o IO): 19.337ms
	Processing time (w/o IO): 20.172ms
	Processing time (w/o IO): 19.256ms
	Processing time (w/o IO): 19.326ms
	Processing time (w/o IO): 19.163ms
	Processing time (w/o IO): 19.041ms
	 Time (mean ± σ):      43.2 ms ±   0.9 ms    [User: 64.9 ms, System: 8.9 ms]
	 Range (min … max):    41.2 ms …  43.9 ms    10 runs
	
Checking output
Success: related_posts_nim_con.json is valid!
Running Nim Concurrent
using 4 threads
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 253.505ms
	Processing time (w/o IO): 253.749ms
	Processing time (w/o IO): 253.7ms
	 Time (mean ± σ):     341.8 ms ±   0.4 ms    [User: 759.8 ms, System: 34.2 ms]
	 Range (min … max):   341.6 ms … 342.1 ms    2 runs
	
Running Nim Concurrent
using 4 threads
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 2448.683ms
	Processing time (w/o IO): 2508.647ms
	Processing time (w/o IO): 2447.064ms
	 Time (mean ± σ):      2.760 s ±  0.039 s    [User: 6.968 s, System: 0.078 s]
	 Range (min … max):    2.732 s …  2.788 s    2 runs
```
*WITH* PGO
**Multi Threaded**
`nim_con` on `main` branch	 
```
(related) michael@azure1:~/repos/related_post_gen$ ./nim_con.sh 
* main
  nim_con_rev
...
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 31.299ms
	Processing time (w/o IO): 31.849ms
	Processing time (w/o IO): 33.879ms
	Processing time (w/o IO): 30.979ms
	Processing time (w/o IO): 31.164ms
	Processing time (w/o IO): 33.213ms
	Processing time (w/o IO): 31.885ms
	Processing time (w/o IO): 31.08ms
	Processing time (w/o IO): 31.684ms
	Processing time (w/o IO): 34.735ms
	Processing time (w/o IO): 33.313ms
	Processing time (w/o IO): 33.399ms
	Processing time (w/o IO): 31.201ms
	 Time (mean ± σ):      56.1 ms ±   1.5 ms    [User: 127.6 ms, System: 8.8 ms]
	 Range (min … max):    54.4 ms …  58.5 ms    10 runs
	
Checking output
Success: related_posts_nim_con.json is valid!
Running Nim Concurrent
using 8 threads
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 448.425ms
	Processing time (w/o IO): 463.625ms
	Processing time (w/o IO): 475.878ms
	 Time (mean ± σ):     557.6 ms ±   8.6 ms    [User: 1716.6 ms, System: 36.1 ms]
	 Range (min … max):   551.5 ms … 563.6 ms    2 runs
	
Running Nim Concurrent
using 8 threads
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 4483.917ms
	Processing time (w/o IO): 4447.62ms
	Processing time (w/o IO): 4387.741ms
	 Time (mean ± σ):      4.694 s ±  0.046 s    [User: 15.380 s, System: 0.074 s]
	 Range (min … max):    4.662 s …  4.726 s    2 runs
```

**Comment by michaelsbradleyjr** [comment]
@inv2004 anything sticks out to you here as needing improvement? Obviously this project's maintainer has the say on what gets merged, but I always appreciate code review/suggestions from another Nim dev. Also, I'm experimenting with [taskpools](https://github.com/status-im/nim-taskpools) and [weave](https://github.com/mratsim/weave) as alternatives to [malebolgia](https://github.com/Araq/malebolgia) for use in `nim_con`. Any other ideas? You may be working on a totally different approach, and that would be cool too.

**Comment by jinyus** [comment]
```
Nim Concurrent:

        Benchmark 1: ./build/related_con
        Processing time (w/o IO): 21.642ms
        Processing time (w/o IO): 20.97ms
        Processing time (w/o IO): 20.944ms
        Processing time (w/o IO): 22.766ms
        Processing time (w/o IO): 21.653ms
        Processing time (w/o IO): 21.319ms
        Processing time (w/o IO): 21.419ms
        Processing time (w/o IO): 21.315ms
        Processing time (w/o IO): 21.183ms
        Processing time (w/o IO): 21.005ms
        Processing time (w/o IO): 21.795ms
        Processing time (w/o IO): 21.956ms
        Processing time (w/o IO): 21.708ms
          Time (mean ± σ):      49.9 ms ±   0.9 ms    [User: 73.1 ms, System: 10.9 ms]
          Range (min … max):    48.2 ms …  50.9 ms    10 runs
         
Nim Concurrent:

        Benchmark 1: ./build/related_con
        Processing time (w/o IO): 297.229ms
        Processing time (w/o IO): 294.407ms
        Processing time (w/o IO): 294.895ms
          Time (mean ± σ):     406.7 ms ±   1.1 ms    [User: 856.7 ms, System: 43.4 ms]
          Range (min … max):   405.9 ms … 407.5 ms    2 runs
         
Nim Concurrent:

        Benchmark 1: ./build/related_con
        Processing time (w/o IO): 2688.544ms
        Processing time (w/o IO): 2679.187ms
        Processing time (w/o IO): 2683.918ms
          Time (mean ± σ):      3.056 s ±  0.002 s    [User: 7.451 s, System: 0.113 s]
          Range (min … max):    3.055 s …  3.058 s    2 runs

```

**Comment by michaelsbradleyjr** [comment]
@jinyus that's this PR branch?

**Comment by jinyus** [comment]
yes, ready to merge?

**Comment by michaelsbradleyjr** [comment]
Sure, go for it.

I'm trying out `gcc` PGO vs. `clang` PGO, forgot to do that earlier per @inv2004's suggestion. If it makes a *consistently significant* difference it will be worth adding PGO steps back in, but that can be done in another PR.

**Comment by inv2004** [comment]
@michaelsbradleyjr Sorry for late response.

At the moment I think that it is hard to make any changes at all, because the VM results does not correlate to local results at all. The reasons for it could be in gcc/clang versions. Because I found that on old ubuntu clang+PGO is just terrible. + gcc is bad too

**Pull request merged**
