### PR TITLE
Add LuaJIT Implementation

### LINKED ISSUE #92: Add LuaJIT Implementation

### PR DESCRIPTION
**Pull request by kokizzu**
fixes #92 

```
alias time='/usr/bin/time -f "\nCPU: %Us\tReal: %es\tRAM: %MKB"'

# go version
go version go1.21.1 linux/amd64

## time go run main.go
Processing time (w/o IO): 18.986578ms

CPU: 0.18s      Real: 0.15s     RAM: 61952KB

# luajit -v

## time luajit luajit_ffi.lua
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/
Processing time (w/o IO):       47.409057617188 ms

CPU: 0.15s      Real: 0.17s     RAM: 25972KB

## time luajit only_lua.lua
Processing time (w/o IO):       46.232938766479 ms

CPU: 0.15s      Real: 0.17s     RAM: 25916KB

# lua -v
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio

## time lua only_lua.lua
Processing time (w/o IO):       1210.4570865631 ms

CPU: 1.52s      Real: 1.53s     RAM: 45228KB

# verify
cat related_posts_go.json| jq > go.json 
cat related_posts_lua.json| jq > lua.json
diff go.json lua.json # empty

### CODE REVIEW

**Comment by kokizzu** [comment]
hmm '__') i believe lua `socket` is built in module

**Comment by kokizzu** [comment]
yes not calling C code, ok will remove ffi part

**Comment by kokizzu** [comment]
ah damn apparently i use system's lua-socket
```
dpkg -l | grep lua-socket
ii  lua-socket:amd64                                 3.0~rc1+git+ac3201d-6                                           amd64        TCP/UDP socket library for the Lua language
```

**Comment by jinyus** [comment]
Installing worked for me:

`sudo luarocks install luasocket`

**Comment by kokizzu** [comment]
try this one? `luarocks --lua-version 5.1 install luasocket` since luajit is on 5.1

**Comment by jinyus** [comment]
Works now, thanks. Does this mean that the both lua and lua5.1 would need to be installed in the github workflow VM?

**Comment by kokizzu** [comment]
only lua5.1 is enough i guess

**Pull request merged**
