### PR TITLE
Added LTO to D build

### PR DESCRIPTION
**Pull request by cyrusmsk**
Added -flto to D
Remove duplicated "llvm" dependency from Dockerfile

### CODE REVIEW

**Comment by cyrusmsk** [comment]
Please if it's possible check if no regression in performance is happening with LTO before merging. Because I'm not sure how exactly it will affect performance inside Docker.

**Comment by delneg** [comment]
"-mcpu=native"
Looks like against the rules, 
> Specific hardware targeting

**Comment by jinyus** [comment]
Correct, I removed it but it didn't make a difference for me.

**Comment by cyrusmsk** [comment]
I saw Nim uses native things as well :)
switch("passC", "-flto -march=native -Ofast")
switch("passL", "-flto -march=native -Ofast")

**Comment by cyrusmsk** [comment]
@jinyus I removed "native" flag from the commit

**Comment by jinyus** [comment]
Having troubles with the build:

```
/usr/bin/ld: cannot find -lphobos2-ldc-lto-shared: No such file or directory
/usr/bin/ld: cannot find -ldruntime-ldc-lto-shared: No such file or directory
collect2: error: ld returned 1 exit status
Error: /usr/bin/cc failed with status: 1
Error /usr/bin/ldc2 failed with exit code 1.
```

libs seems to be installed:

```
▬▶ ls /usr/lib | grep phobos
lrwxrwxrwx 1 root root    19 Aug  2 02:06 libgphobos.so -> libgphobos.so.4.0.0
lrwxrwxrwx 1 root root    19 Aug  2 02:06 libgphobos.so.4 -> libgphobos.so.4.0.0
-rwxr-xr-x 1 root root   24M Aug  2 02:06 libgphobos.so.4.0.0
-rw-r--r-- 1 root root  9.4M Sep  3 14:51 libphobos2-ldc.a
-rw-r--r-- 1 root root   19M Sep  3 14:51 libphobos2-ldc-debug.a
lrwxrwxrwx 1 root root    34 Sep  3 14:51 libphobos2-ldc-debug-shared.so -> libphobos2-ldc-debug-shared.so.104
lrwxrwxrwx 1 root root    36 Sep  3 14:51 libphobos2-ldc-debug-shared.so.104 -> libphobos2-ldc-debug-shared.so.104.2
-rwxr-xr-x 1 root root   12M Sep  3 14:51 libphobos2-ldc-debug-shared.so.104.2
-rw-r--r-- 1 root root  8.2M Sep  3 14:51 libphobos2-ldc-lto.a
lrwxrwxrwx 1 root root    28 Sep  3 14:51 libphobos2-ldc-shared.so -> libphobos2-ldc-shared.so.104
lrwxrwxrwx 1 root root    30 Sep  3 14:51 libphobos2-ldc-shared.so.104 -> libphobos2-ldc-shared.so.104.2
-rwxr-xr-x 1 root root  6.3M Sep  3 14:51 libphobos2-ldc-shared.so.104.2


▬▶ ls /usr/lib | grep drun
-rw-r--r-- 1 root root  2.8M Sep  3 14:51 libdruntime-ldc.a
-rw-r--r-- 1 root root  5.9M Sep  3 14:51 libdruntime-ldc-debug.a
lrwxrwxrwx 1 root root    35 Sep  3 14:51 libdruntime-ldc-debug-shared.so -> libdruntime-ldc-debug-shared.so.104
lrwxrwxrwx 1 root root    37 Sep  3 14:51 libdruntime-ldc-debug-shared.so.104 -> libdruntime-ldc-debug-shared.so.104.2
-rwxr-xr-x 1 root root  3.3M Sep  3 14:51 libdruntime-ldc-debug-shared.so.104.2
-rw-r--r-- 1 root root  2.6M Sep  3 14:51 libdruntime-ldc-lto.a
lrwxrwxrwx 1 root root    29 Sep  3 14:51 libdruntime-ldc-shared.so -> libdruntime-ldc-shared.so.104
lrwxrwxrwx 1 root root    31 Sep  3 14:51 libdruntime-ldc-shared.so.104 -> libdruntime-ldc-shared.so.104.2
-rwxr-xr-x 1 root root  1.8M Sep  3 14:51 libdruntime-ldc-shared.so.104.2
lrwxrwxrwx 1 root root    21 Aug  2 02:06 libgdruntime.so -> libgdruntime.so.4.0.0
lrwxrwxrwx 1 root root    21 Aug  2 02:06 libgdruntime.so.4 -> libgdruntime.so.4.0.0
-rwxr-xr-x 1 root root  4.5M Aug  2 02:06 libgdruntime.so.4.0.0

```

**Comment by cyrusmsk** [comment]
@delneg sorry for this misunderstanding. I thought specific hardware if in the options specific parameters CPU are defined. Like "Broadwell". So the compiler will know exactly about specific instructions. And Native is more like "Scala Native".

**Comment by cyrusmsk** [comment]
@jinyus I've added flag that should say the linker to not use default things and use LTO instead.

**Comment by jinyus** [comment]
Massive degradation for me:

```
Benchmark 1: ./related
Processing time (w/o IO): 60.57ms
Processing time (w/o IO): 61.982ms
Processing time (w/o IO): 56.092ms
Processing time (w/o IO): 57.916ms
Processing time (w/o IO): 55.976ms
Processing time (w/o IO): 63.48ms
Processing time (w/o IO): 62.406ms
Processing time (w/o IO): 59.616ms
Processing time (w/o IO): 61.124ms
Processing time (w/o IO): 57.14ms
Processing time (w/o IO): 62.557ms
Processing time (w/o IO): 63.562ms
Processing time (w/o IO): 56.219ms
  Time (mean ± σ):     132.9 ms ±   5.2 ms    [User: 122.6 ms, System: 15.9 ms]
  Range (min … max):   126.1 ms … 142.2 ms    10 runs
```

old: 

```
Benchmark 1: ./related
Processing time (w/o IO): 16.842ms
Processing time (w/o IO): 23.036ms
Processing time (w/o IO): 17.739ms
Processing time (w/o IO): 17.384ms
Processing time (w/o IO): 17.792ms
Processing time (w/o IO): 17.165ms
Processing time (w/o IO): 16.824ms
Processing time (w/o IO): 16.843ms
Processing time (w/o IO): 17.829ms
Processing time (w/o IO): 16.999ms
Processing time (w/o IO): 17.37ms
Processing time (w/o IO): 16.308ms
Processing time (w/o IO): 16.906ms
  Time (mean ± σ):      80.0 ms ±   3.2 ms    [User: 61.8 ms, System: 20.8 ms]
  Range (min … max):    75.1 ms …  84.7 ms    10 runs
```

**Comment by cyrusmsk** [comment]
Thanks. Then let's save that we have now.

**Pull request closed without merging**
