### PR TITLE
[Nim] adapt approaches in nim_con to to single-threaded impl and improve perf in both

### PR DESCRIPTION
**Pull request by michaelsbradleyjr**
As I mentioned in #300, I'm trying things out on a free tier Azure VM with the same specs as your benchmarking VM.

With changes in this PR, I'm seeing some speedups
```
Nim Concurrent:

        Benchmark 1: ./build/related_con
        Processing time (w/o IO): 23.264ms
        Processing time (w/o IO): 22.754ms
        Processing time (w/o IO): 22.866ms
        Processing time (w/o IO): 22.699ms
        Processing time (w/o IO): 22.644ms
        Processing time (w/o IO): 22.95ms
        Processing time (w/o IO): 22.575ms
        Processing time (w/o IO): 22.785ms
        Processing time (w/o IO): 22.73ms
        Processing time (w/o IO): 22.623ms
        Processing time (w/o IO): 22.603ms
        Processing time (w/o IO): 22.645ms
        Processing time (w/o IO): 22.583ms
          Time (mean ± σ):      45.2 ms ±   0.8 ms    [User: 77.1 ms, System: 7.0 ms]
          Range (min … max):    43.8 ms …  46.6 ms    10 runs
         
Nim Concurrent:

        Benchmark 1: ./build/related_con
        Processing time (w/o IO): 309.609ms
        Processing time (w/o IO): 313.802ms
        Processing time (w/o IO): 314.481ms
          Time (mean ± σ):     411.4 ms ±   6.8 ms    [User: 955.1 ms, System: 42.3 ms]
          Range (min … max):   406.6 ms … 416.3 ms    2 runs
         
Nim Concurrent:

        Benchmark 1: ./build/related_con
        Processing time (w/o IO): 3214.735ms
        Processing time (w/o IO): 2883.433ms
        Processing time (w/o IO): 2883.317ms
          Time (mean ± σ):      3.164 s ±  0.001 s    [User: 8.772 s, System: 0.078 s]
          Range (min … max):    3.164 s …  3.165 s    2 runs
          
Nim:

        Benchmark 1: ./related
        Processing time (w/o IO): 27.721ms
        Processing time (w/o IO): 27.495ms
        Processing time (w/o IO): 27.446ms
        Processing time (w/o IO): 27.396ms
        Processing time (w/o IO): 27.313ms
        Processing time (w/o IO): 27.65ms
        Processing time (w/o IO): 27.512ms
        Processing time (w/o IO): 27.363ms
        Processing time (w/o IO): 27.346ms
        Processing time (w/o IO): 27.336ms
        Processing time (w/o IO): 27.423ms
        Processing time (w/o IO): 27.309ms
        Processing time (w/o IO): 27.504ms
          Time (mean ± σ):      49.6 ms ±   0.5 ms    [User: 40.1 ms, System: 9.5 ms]
          Range (min … max):    49.1 ms …  50.9 ms    10 runs
         
Nim:

        Benchmark 1: ./related
        Processing time (w/o IO): 379.217ms
        Processing time (w/o IO): 380.812ms
        Processing time (w/o IO): 379.355ms
          Time (mean ± σ):     467.8 ms ±   0.2 ms    [User: 435.8 ms, System: 31.9 ms]
          Range (min … max):   467.6 ms … 468.0 ms    2 runs
         
Nim:

        Benchmark 1: ./related
        Processing time (w/o IO): 3400.621ms
        Processing time (w/o IO): 3398.67ms
        Processing time (w/o IO): 3399.28ms
          Time (mean ± σ):      3.680 s ±  0.002 s    [User: 3.599 s, System: 0.076 s]
          Range (min … max):    3.678 s …  3.681 s    2 runs
```
There seems to be a lot of runtime variability in the VM, probably because the box it's running on is more/less busy at various times.

So I'm not confident you'll get improved numbers, i.e. it might flip around again with `nim_con` being slower than `nim`, but let's see how it goes.

I've tried to explain clearly the why/what in each  commit message. I didn't completely overhaul the structure and code of `nim`, just adapted some of what I did in `nim_con` where it seemed like it should speedup the single-threaded impl.

I have some ideas about switching to a different task manager library for `nim_con`. There are several promising options besides `malebolgia` and they each take different approaches. Maybe one of those approaches will be better suited to the Azure VM environment, will be interesting to see how it goes.

### CODE REVIEW

**Comment by jinyus** [comment]
Ran 3 times with the same results:

```
Nim:

        Benchmark 1: ./related
        Processing time (w/o IO): 31.314ms
        Processing time (w/o IO): 31.293ms
        Processing time (w/o IO): 30.912ms
        Processing time (w/o IO): 31.081ms
        Processing time (w/o IO): 31.201ms
        Processing time (w/o IO): 31.258ms
        Processing time (w/o IO): 31.206ms
        Processing time (w/o IO): 31.268ms
        Processing time (w/o IO): 30.987ms
        Processing time (w/o IO): 31.117ms
        Processing time (w/o IO): 30.878ms
        Processing time (w/o IO): 31.215ms
        Processing time (w/o IO): 31.067ms
          Time (mean ± σ):      57.3 ms ±   0.3 ms    [User: 48.6 ms, System: 8.7 ms]
          Range (min … max):    56.6 ms …  57.6 ms    10 runs
         
Nim:

        Benchmark 1: ./related
        Processing time (w/o IO): 438.542ms
        Processing time (w/o IO): 439.15ms
        Processing time (w/o IO): 438.326ms
          Time (mean ± σ):     541.8 ms ±   0.9 ms    [User: 498.0 ms, System: 43.7 ms]
          Range (min … max):   541.2 ms … 542.5 ms    2 runs
         
Nim:

        Benchmark 1: ./related
        Processing time (w/o IO): 3867.711ms
        Processing time (w/o IO): 3871.571ms
        Processing time (w/o IO): 3863.995ms
          Time (mean ± σ):      4.236 s ±  0.027 s    [User: 4.127 s, System: 0.093 s]
          Range (min … max):    4.217 s …  4.255 s    2 runs
```

**Comment by jinyus** [comment]
Fresh run from main branch:

`sudo docker run -it --rm -e TEST_NAME=nim databench`

```
Nim:

        Benchmark 1: ./related
        Processing time (w/o IO): 30.636ms
        Processing time (w/o IO): 30.399ms
        Processing time (w/o IO): 30.472ms
        Processing time (w/o IO): 30.361ms
        Processing time (w/o IO): 30.541ms
        Processing time (w/o IO): 30.471ms
        Processing time (w/o IO): 30.436ms
        Processing time (w/o IO): 30.597ms
        Processing time (w/o IO): 30.448ms
        Processing time (w/o IO): 30.367ms
        Processing time (w/o IO): 30.223ms
        Processing time (w/o IO): 30.442ms
        Processing time (w/o IO): 30.69ms
          Time (mean ± σ):      56.1 ms ±   0.6 ms    [User: 45.2 ms, System: 10.9 ms]
          Range (min … max):    55.2 ms …  57.2 ms    10 runs
         
Nim:

        Benchmark 1: ./related
        Processing time (w/o IO): 441.369ms
        Processing time (w/o IO): 435.063ms
        Processing time (w/o IO): 433.216ms
          Time (mean ± σ):     533.4 ms ±   1.4 ms    [User: 495.9 ms, System: 37.4 ms]
          Range (min … max):   532.4 ms … 534.4 ms    2 runs
         
Nim:

        Benchmark 1: ./related
        Processing time (w/o IO): 3825.508ms
        Processing time (w/o IO): 3820.796ms
        Processing time (w/o IO): 3817.013ms
          Time (mean ± σ):      4.170 s ±  0.003 s    [User: 4.051 s, System: 0.109 s]
          Range (min … max):    4.168 s …  4.172 s    2 runs
```

**Comment by jinyus** [comment]
Post a fresh run from main branch on your VM

**Comment by michaelsbradleyjr** [comment]
Working on it.

Just curious, what Azure datacenter is your VM in?  If you don't want to say for some reason, no problem. Mine's in East US 2.

**Comment by jinyus** [comment]
Location: East US 2 (Zone 1)

**Comment by michaelsbradleyjr** [comment]
I took a few minutes to improve my workflow. Then I realized I screwed up the copy/paste so did fresh runs just to make sure it's not flipped around. Sorry for the delay.

On my VM, `nim` on `main` and `nim_rev` branches are super close, with `main` slightly ahead, but `nim_con` on nim_rev pulls ahead in terms of performance.

Before hitting the *Comment* button, I did even more runs and have now seen the "winner" flipped around all possible ways: sometimes `nim` on `nim_rev` ahead of `nim` on `main`, `nim_con` on `nim_rev` losing to both of those, etc.

So... sadly, for small-ish deltas in ms runtimes, it seems an Azure VM is inconsistent, and given the nature of cloud servers, I guess that's not surprising. And I guess there's not much that can be done about it.

**main** `nim`
```
(related) michael@azure1:~/repos/related_post_gen$ git branch
* main
  nim_rev
(related) michael@azure1:~/repos/related_post_gen$ ./nim.sh
Running Nim
  Verifying dependencies for related@0.1.0
     Info:  Dependency on jsony@any version already satisfied
  Verifying dependencies for jsony@1.1.5
     Info:  Dependency on xxhash@any version already satisfied
  Verifying dependencies for xxhash@0.9.0
  Verifying dependencies for related@0.1.0
     Info:  Dependency on jsony@any version already satisfied
  Verifying dependencies for jsony@1.1.5
     Info:  Dependency on xxhash@any version already satisfied
  Verifying dependencies for xxhash@0.9.0
  Executing task buildopt in /home/michael/repos/related_post_gen/nim/related.nimble
  Verifying dependencies for related@0.1.0
     Info:  Dependency on jsony@any version already satisfied
  Verifying dependencies for jsony@1.1.5
     Info:  Dependency on xxhash@any version already satisfied
  Verifying dependencies for xxhash@0.9.0
   Building related/related using c backend
Build with profileGen
Gen stat 1/10
Gen stat 2/10
Gen stat 3/10
Gen stat 4/10
Gen stat 5/10
Gen stat 6/10
Gen stat 7/10
Gen stat 8/10
Gen stat 9/10
Gen stat 10/10
  Verifying dependencies for related@0.1.0
     Info:  Dependency on jsony@any version already satisfied
  Verifying dependencies for jsony@1.1.5
     Info:  Dependency on xxhash@any version already satisfied
  Verifying dependencies for xxhash@0.9.0
   Building related/related using c backend
Build with profileUse
Nim:

	Benchmark 1: ./related
	Processing time (w/o IO): 27.148ms
	Processing time (w/o IO): 26.821ms
	Processing time (w/o IO): 26.897ms
	Processing time (w/o IO): 27.046ms
	Processing time (w/o IO): 27.004ms
	Processing time (w/o IO): 26.919ms
	Processing time (w/o IO): 26.971ms
	Processing time (w/o IO): 27.069ms
	Processing time (w/o IO): 27.277ms
	Processing time (w/o IO): 26.794ms
	Processing time (w/o IO): 26.932ms
	Processing time (w/o IO): 27.018ms
	Processing time (w/o IO): 27.074ms
	 Time (mean ± σ):      49.7 ms ±   0.5 ms    [User: 41.5 ms, System: 8.2 ms]
	 Range (min … max):    48.7 ms …  50.4 ms    10 runs
	
Checking output
Success: related_posts_nim.json is valid!
Running Nim
Nim:

	Benchmark 1: ./related
	Processing time (w/o IO): 375.715ms
	Processing time (w/o IO): 376.057ms
	Processing time (w/o IO): 376.481ms
	 Time (mean ± σ):     467.3 ms ±   2.1 ms    [User: 442.8 ms, System: 24.4 ms]
	 Range (min … max):   465.8 ms … 468.8 ms    2 runs
	
Running Nim
Nim:

	Benchmark 1: ./related
	Processing time (w/o IO): 3362.928ms
	Processing time (w/o IO): 3354.533ms
	Processing time (w/o IO): 3360.227ms
	 Time (mean ± σ):      3.630 s ±  0.000 s    [User: 3.550 s, System: 0.076 s]
	 Range (min … max):    3.629 s …  3.630 s    2 runs
```
**nim_rev** `nim`
```
(related) michael@azure1:~/repos/related_post_gen$ ./nim.sh
Running Nim
  Verifying dependencies for related@0.1.0
     Info:  Dependency on jsony@#head already satisfied
  Verifying dependencies for jsony@1.1.5
     Info:  Dependency on xxhash@any version already satisfied
  Verifying dependencies for xxhash@0.9.0
  Verifying dependencies for related@0.1.0
     Info:  Dependency on jsony@#head already satisfied
  Verifying dependencies for jsony@1.1.5
     Info:  Dependency on xxhash@any version already satisfied
  Verifying dependencies for xxhash@0.9.0
  Executing task buildopt in /home/michael/repos/related_post_gen/nim/related.nimble
  Verifying dependencies for related@0.1.0
     Info:  Dependency on jsony@#head already satisfied
  Verifying dependencies for jsony@1.1.5
     Info:  Dependency on xxhash@any version already satisfied
  Verifying dependencies for xxhash@0.9.0
   Building related/related using c backend
Build with profileGen
Gen stat
     Info:  Nimble data file "/home/michael/.nimble/nimbledata2.json" has been loaded.
  Verifying dependencies for related@0.1.0
    Reading official package list
   Checking for jsony@#head
     Info:  Dependency on jsony@#head already satisfied
  Verifying dependencies for jsony@1.1.5
    Reading official package list
   Checking for xxhash@any version
     Info:  Dependency on xxhash@any version already satisfied
  Verifying dependencies for xxhash@0.9.0
   Building related/related using c backend
  Executing /home/michael/.nimble/bin/nim c --colors:on --noNimblePath -d:profileUse -d:release -d:NimblePkgVersion=0.1.0 --path:/home/michael/.nimble/pkgs2/jsony-1.1.5-143f6938d399f92f5bf6c7dcf4e589f2b28634db --path:/home/michael/.nimble/pkgs2/xxhash-0.9.0-5555c44b94f28943587a16bb1f0a433010ffb702 -o:/home/michael/repos/related_post_gen/nim/related /home/michael/repos/related_post_gen/nim/src/related.nim
Build with profileUse
Hint: used config file '/home/michael/.choosenim/toolchains/nim-2.0.0/config/nim.cfg' [Conf]
Hint: used config file '/home/michael/.choosenim/toolchains/nim-2.0.0/config/config.nims' [Conf]
Hint: used config file '/home/michael/repos/related_post_gen/nim/config.nims' [Conf]
............................................................................................................
CC: xxhash
CC: ../../../../.choosenim/toolchains/nim-2.0.0/lib/system/exceptions.nim
CC: ../../../../.choosenim/toolchains/nim-2.0.0/lib/std/private/digitsutils.nim
CC: ../../../../.choosenim/toolchains/nim-2.0.0/lib/std/assertions.nim
CC: ../../../../.choosenim/toolchains/nim-2.0.0/lib/std/formatfloat.nim
CC: ../../../../.choosenim/toolchains/nim-2.0.0/lib/system/dollars.nim
CC: ../../../../.choosenim/toolchains/nim-2.0.0/lib/std/syncio.nim
CC: ../../../../.choosenim/toolchains/nim-2.0.0/lib/system.nim
CC: ../../../../.choosenim/toolchains/nim-2.0.0/lib/pure/parseutils.nim
CC: ../../../../.choosenim/toolchains/nim-2.0.0/lib/pure/math.nim
CC: ../../../../.choosenim/toolchains/nim-2.0.0/lib/pure/unicode.nim
CC: ../../../../.choosenim/toolchains/nim-2.0.0/lib/pure/strutils.nim
CC: ../../../../.choosenim/toolchains/nim-2.0.0/lib/pure/times.nim
CC: ../../../../.choosenim/toolchains/nim-2.0.0/lib/std/monotimes.nim
CC: ../../../../.nimble/pkgs2/jsony-1.1.5-143f6938d399f92f5bf6c7dcf4e589f2b28634db/jsony.nim
CC: ../../../../.nimble/pkgs2/xxhash-0.9.0-5555c44b94f28943587a16bb1f0a433010ffb702/xxhash.nim
CC: fixedtable.nim
CC: related.nim
Hint:  [Link]
Hint: mm: arc; opt: speed; options: -d:release
88528 lines; 3.124s; 137.145MiB peakmem; proj: /home/michael/repos/related_post_gen/nim/src/related.nim; out: /home/michael/repos/related_post_gen/nim/related [SuccessX]
     Info:  Nimble data file "/home/michael/.nimble/nimbledata2.json" has been saved.
Nim:

	Benchmark 1: ./related
	Processing time (w/o IO): 27.85ms
	Processing time (w/o IO): 27.584ms
	Processing time (w/o IO): 28.002ms
	Processing time (w/o IO): 27.597ms
	Processing time (w/o IO): 27.445ms
	Processing time (w/o IO): 27.348ms
	Processing time (w/o IO): 27.465ms
	Processing time (w/o IO): 27.551ms
	Processing time (w/o IO): 27.519ms
	Processing time (w/o IO): 27.46ms
	Processing time (w/o IO): 27.505ms
	Processing time (w/o IO): 27.581ms
	Processing time (w/o IO): 27.478ms
	 Time (mean ± σ):      50.0 ms ±   0.6 ms    [User: 42.0 ms, System: 8.0 ms]
	 Range (min … max):    49.1 ms …  51.1 ms    10 runs
	
Checking output
Success: related_posts_nim.json is valid!
Running Nim
Nim:

	Benchmark 1: ./related
	Processing time (w/o IO): 378.184ms
	Processing time (w/o IO): 378.625ms
	Processing time (w/o IO): 379.395ms
	 Time (mean ± σ):     466.9 ms ±   2.6 ms    [User: 434.5 ms, System: 32.4 ms]
	 Range (min … max):   465.1 ms … 468.8 ms    2 runs
	
Running Nim
Nim:

	Benchmark 1: ./related
	Processing time (w/o IO): 3406.995ms
	Processing time (w/o IO): 3403.228ms
	Processing time (w/o IO): 3406.073ms
	 Time (mean ± σ):      3.691 s ±  0.004 s    [User: 3.598 s, System: 0.086 s]
	 Range (min … max):    3.688 s …  3.694 s    2 runs
```
**nim_rev** `nim_con`
```
(related) michael@azure1:~/repos/related_post_gen$ git branch
  main
* nim_rev
(related) michael@azure1:~/repos/related_post_gen$ ./nim_con.sh 
Running Nim Concurrent
using 4 threads
  Verifying dependencies for related_con@0.1.0
     Info:  Dependency on jsony@#head already satisfied
  Verifying dependencies for jsony@1.1.5
     Info:  Dependency on malebolgia@#head already satisfied
  Verifying dependencies for malebolgia@1.3.1
     Info:  Dependency on xxhash@any version already satisfied
  Verifying dependencies for xxhash@0.9.0
Compiling profiled executable
Generating profile
Compiling optimized executable
Hint: used config file '/home/michael/.choosenim/toolchains/nim-2.0.0/config/nim.cfg' [Conf]
Hint: used config file '/home/michael/.choosenim/toolchains/nim-2.0.0/config/config.nims' [Conf]
Hint: used config file '/home/michael/repos/related_post_gen/nim_con/config.nims' [Conf]
..............................................................................................................................................
CC: xxhash
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/system/exceptions.nim
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/std/private/digitsutils.nim
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/std/assertions.nim
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/std/formatfloat.nim
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/system/dollars.nim
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/std/typedthreads.nim
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/std/syncio.nim
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/system.nim
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/pure/parseutils.nim
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/pure/math.nim
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/pure/unicode.nim
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/pure/strutils.nim
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/pure/times.nim
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/std/monotimes.nim
CC: ../../../.nimble/pkgs2/jsony-1.1.5-143f6938d399f92f5bf6c7dcf4e589f2b28634db/jsony.nim
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/std/isolation.nim
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/std/tasks.nim
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/std/envvars.nim
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/std/cmdline.nim
CC: ../../../.choosenim/toolchains/nim-2.0.0/lib/pure/os.nim
CC: ../../../.nimble/pkgs2/malebolgia-1.3.1-3b6b8b0899c60390dd20453c5f7a2a015362cf03/malebolgia.nim
CC: ../../../.nimble/pkgs2/xxhash-0.9.0-5555c44b94f28943587a16bb1f0a433010ffb702/xxhash.nim
CC: related_con/fixedtable.nim
CC: related_con.nim
Hint:  [Link]
Hint: mm: arc; threads: on; opt: speed; options: -d:release
95824 lines; 3.287s; 137.02MiB peakmem; proj: /home/michael/repos/related_post_gen/nim_con/related_con.nim; out: /home/michael/repos/related_post_gen/nim_con/build/related_con [SuccessX]
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 22.741ms
	Processing time (w/o IO): 22.794ms
	Processing time (w/o IO): 22.779ms
	Processing time (w/o IO): 22.744ms
	Processing time (w/o IO): 22.82ms
	Processing time (w/o IO): 22.759ms
	Processing time (w/o IO): 23.028ms
	Processing time (w/o IO): 22.707ms
	Processing time (w/o IO): 22.904ms
	Processing time (w/o IO): 22.902ms
	Processing time (w/o IO): 22.729ms
	Processing time (w/o IO): 23.009ms
	Processing time (w/o IO): 23.105ms
	 Time (mean ± σ):      46.9 ms ±   0.6 ms    [User: 77.4 ms, System: 8.2 ms]
	 Range (min … max):    46.0 ms …  47.8 ms    10 runs
	
Checking output
Success: related_posts_nim_con.json is valid!
Running Nim Concurrent
using 4 threads
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 313.669ms
	Processing time (w/o IO): 314.099ms
	Processing time (w/o IO): 312.339ms
	 Time (mean ± σ):     406.9 ms ±   5.3 ms    [User: 960.7 ms, System: 36.0 ms]
	 Range (min … max):   403.1 ms … 410.6 ms    2 runs
	
Running Nim Concurrent
using 4 threads
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 2894.673ms
	Processing time (w/o IO): 2885.285ms
	Processing time (w/o IO): 2903.007ms
	 Time (mean ± σ):      3.206 s ±  0.011 s    [User: 8.794 s, System: 0.078 s]
	 Range (min … max):    3.198 s …  3.214 s    2 runs
```

**Comment by michaelsbradleyjr** [comment]
I did some extra cleanup and started experimenting with alternative task manager libs.

One thing I realized is that I hadn't tried disabling PGO in combination with latest changes (before switching task managers). When I did that, I'm seeing better numbers in Azure VM for both the single-threaded and multi-threaded impls. See below.

It may be that given how streamlined the code is at this point that PGO is doing more harm than help, but I don't have a deeper technical explanation yet.

Switching to a different task manager lib may shave more time off `nim_con`, but the jury's still out and I don't have a PR ready for that just yet.

*WITHOUT PGO*

**Single Threaded**
`nim` on `nim_rev` branch
```
(related) michael@azure1:~/repos/related_post_gen$ git branch
  main
* nim_rev
(related) michael@azure1:~/repos/related_post_gen$ python gen_fake_posts.py 5000
(related) michael@azure1:~/repos/related_post_gen$ ./run.sh nim raw_results.md append
Running Nim
Nim:

	Benchmark 1: ./related
	Processing time (w/o IO): 27.153ms
	Processing time (w/o IO): 26.915ms
	Processing time (w/o IO): 26.956ms
	 Time (mean ± σ):      48.8 ms ±   0.2 ms    [User: 40.3 ms, System: 8.4 ms]
	 Range (min … max):    48.7 ms …  48.9 ms    2 runs
	
(related) michael@azure1:~/repos/related_post_gen$ python gen_fake_posts.py 20000
(related) michael@azure1:~/repos/related_post_gen$ ./run.sh nim raw_results.md append
Running Nim
Nim:

	Benchmark 1: ./related
	Processing time (w/o IO): 376.045ms
	Processing time (w/o IO): 378.792ms
	Processing time (w/o IO): 375.689ms
	 Time (mean ± σ):     460.4 ms ±   2.2 ms    [User: 440.5 ms, System: 19.9 ms]
	 Range (min … max):   458.9 ms … 462.0 ms    2 runs
	
(related) michael@azure1:~/repos/related_post_gen$ python gen_fake_posts.py 60000
(related) michael@azure1:~/repos/related_post_gen$ ./run.sh nim raw_results.md append
Running Nim
Nim:

	Benchmark 1: ./related
	Processing time (w/o IO): 3404.1ms
	Processing time (w/o IO): 3402.396ms
	Processing time (w/o IO): 3400.409ms
	 Time (mean ± σ):      3.657 s ±  0.003 s    [User: 3.604 s, System: 0.048 s]
	 Range (min … max):    3.655 s …  3.660 s    2 runs
```
**Multi Threaded**
`nim_con` on `nim_rev` branch	 
```
(related) michael@azure1:~/repos/related_post_gen$ git branch
  main
* nim_rev
(related) michael@azure1:~/repos/related_post_gen$ python gen_fake_posts.py 5000
(related) michael@azure1:~/repos/related_post_gen$ ./run.sh nim_con raw_results.md append
Running Nim Concurrent
using 4 threads
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 20.032ms
	Processing time (w/o IO): 19.572ms
	Processing time (w/o IO): 19.551ms
	 Time (mean ± σ):      42.5 ms ±   0.4 ms    [User: 63.3 ms, System: 9.9 ms]
	 Range (min … max):    42.2 ms …  42.8 ms    2 runs
	
(related) michael@azure1:~/repos/related_post_gen$ python gen_fake_posts.py 20000
(related) michael@azure1:~/repos/related_post_gen$ ./run.sh nim_con raw_results.md append
Running Nim Concurrent
using 4 threads
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 252.794ms
	Processing time (w/o IO): 252.441ms
	Processing time (w/o IO): 252.109ms
	 Time (mean ± σ):     338.3 ms ±   1.2 ms    [User: 757.0 ms, System: 31.7 ms]
	 Range (min … max):   337.4 ms … 339.2 ms    2 runs
	
(related) michael@azure1:~/repos/related_post_gen$ python gen_fake_posts.py 60000
(related) michael@azure1:~/repos/related_post_gen$ ./run.sh nim_con raw_results.md append
Running Nim Concurrent
using 4 threads
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 2450.163ms
	Processing time (w/o IO): 2448.861ms
	Processing time (w/o IO): 2449.937ms
	 Time (mean ± σ):      2.726 s ±  0.003 s    [User: 6.936 s, System: 0.068 s]
	 Range (min … max):    2.724 s …  2.729 s    2 runs
```

**Comment by michaelsbradleyjr** [comment]
I think this can be closed in view of #335. Changes to the single-threaded impl can be revisited in a future PR.

**Pull request closed without merging**
