### PR TITLE
Concurrent Julia - testing the waters

### PR DESCRIPTION
**Pull request by algunion**
This is the first attempt at a concurrent Julia version.

### CODE REVIEW

**Review by algunion — COMMENTED** [review]
Thanks. Missed that.

**Comment by jinyus** [comment]
concurrent version is 3x slower for me

**Comment by algunion** [comment]
> concurrent version is 3x slower for me

On my end, the parallel version does 8ms (form 21ms for the non-parallel version).

Is the warming up working properly? 

I can push a version with the warming call (so we make sure we do not count the compiler time).

**Comment by jinyus** [comment]
I added the warm up call. It's 7ms now

**Pull request merged**
