### PR TITLE
[Nim Con] proper use of lent, reintroduce xxhash

### PR DESCRIPTION
**Pull request by michaelsbradleyjr**
A small set of changes boosting performance.

Many thanks to @beef331 for answering my questions about `lent`.

### CODE REVIEW

**Comment by michaelsbradleyjr** [comment]
Numbers in my Azure VM/Docker look promising!
```
Run Benchmark (5k posts)
Running Nim Concurrent
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 13.641ms
	Processing time (w/o IO): 12.764ms
	Processing time (w/o IO): 13.09ms
	Processing time (w/o IO): 12.451ms
	Processing time (w/o IO): 14.394ms
	Processing time (w/o IO): 12.354ms
	Processing time (w/o IO): 16.1ms
	Processing time (w/o IO): 12.43ms
	Processing time (w/o IO): 14.077ms
	Processing time (w/o IO): 13.018ms
	Processing time (w/o IO): 12.362ms
	Processing time (w/o IO): 14.306ms
	Processing time (w/o IO): 13.308ms
	 Time (mean ± σ):      41.9 ms ±   1.9 ms    [User: 66.4 ms, System: 10.4 ms]
	 Range (min … max):    40.1 ms …  45.4 ms    10 runs
	
Checking output
Success: related_posts_nim_con.json is valid!
Generate 20000 posts
Run Benchmark (20000 posts)
Running Nim Concurrent
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 176.385ms
	Processing time (w/o IO): 172.697ms
	Processing time (w/o IO): 172.953ms
	 Time (mean ± σ):     291.2 ms ±   1.3 ms    [User: 761.9 ms, System: 33.3 ms]
	 Range (min … max):   290.3 ms … 292.1 ms    2 runs
	
Generate 60000 posts
Run Benchmark (60000 posts)
Running Nim Concurrent
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 1478.88ms
	Processing time (w/o IO): 1484.009ms
	Processing time (w/o IO): 1480.76ms
	 Time (mean ± σ):      1.886 s ±  0.000 s    [User: 6.175 s, System: 0.109 s]
	 Range (min … max):    1.886 s …  1.886 s    2 runs
```

**Comment by jinyus** [comment]
```
Nim Concurrent:

        Benchmark 1: ./build/related_con
        Processing time (w/o IO): 13.728ms
        Processing time (w/o IO): 13.541ms
        Processing time (w/o IO): 13.468ms
        Processing time (w/o IO): 13.447ms
        Processing time (w/o IO): 13.233ms
        Processing time (w/o IO): 13.067ms
        Processing time (w/o IO): 12.101ms
        Processing time (w/o IO): 12.313ms
        Processing time (w/o IO): 14.617ms
        Processing time (w/o IO): 13.995ms
        Processing time (w/o IO): 12.091ms
        Processing time (w/o IO): 13.62ms
        Processing time (w/o IO): 13.359ms
          Time (mean ± σ):      39.3 ms ±   0.7 ms    [User: 65.2 ms, System: 9.3 ms]
          Range (min … max):    38.3 ms …  40.7 ms    10 runs
         
Nim Concurrent:

        Benchmark 1: ./build/related_con
        Processing time (w/o IO): 171.692ms
        Processing time (w/o IO): 171.792ms
        Processing time (w/o IO): 171.078ms
          Time (mean ± σ):     282.5 ms ±   1.9 ms    [User: 747.5 ms, System: 35.7 ms]
          Range (min … max):   281.1 ms … 283.9 ms    2 runs
         
Nim Concurrent:

        Benchmark 1: ./build/related_con
        Processing time (w/o IO): 1473.016ms
        Processing time (w/o IO): 1473.189ms
        Processing time (w/o IO): 1473.502ms
          Time (mean ± σ):      1.842 s ±  0.000 s    [User: 6.112 s, System: 0.099 s]
          Range (min … max):    1.841 s …  1.842 s    2 runs
```

**Comment by cyrusmsk** [comment]
@michaelsbradleyjr can you please explain a bit logic of overloading [] for tag map? Because it looks like ".addr" is unsafe operation https://github.com/nim-lang/RFCs/issues/369:
`The distinction between unsafeAddr and addr makes little sense: addr is already unsafe and unsafeAddr is only a tiny little bit "unsafer", whatever that even means. In practice, I think the distinction never found a bug, you use 'addr', the compiler complains, you use 'unsafeAddr' instead, "problem solved".`

**Comment by beef331** [comment]
It's 'unsafe' in that if you don't know what you're doing it can bite you, in this case we're using it to use the `var Table`'s `[]` which means we can use `lent T`.

**Comment by cyrusmsk** [comment]
So it is kind of pointer https://nim-lang.org/docs/destructors.html#lent-type:
`lent T is like var T a hidden pointer.`

@schveiguy do you think it is the same logic as we could use .ptr for arrays?

**Comment by beef331** [comment]
Yea it's read only pointer that is memory safe.

**Pull request merged**
