### PR TITLE
[D] Chunked sequential version

### PR DESCRIPTION
**Pull request by cyrusmsk**
Added chunked optimization technique to the sequential code.
The idea and implementation of the optimization by Bruce Carneal.

@jinyus Could you please check the performance in VM, before the merge.
Thank you in advance.

### CODE REVIEW

**Comment by jinyus** [comment]
Faster but I'd like to separate the implementations. You can choose an appropriate name, maybe `d_chunked_opt`.

Main:
`D | 24.86 ms | 314.37 ms | 2.71 s`

This PR:
```
D:

        Benchmark 1: ./related
        Processing time (w/o IO): 22.192ms
        Processing time (w/o IO): 21.917ms
        Processing time (w/o IO): 21.58ms
        Processing time (w/o IO): 22.099ms
        Processing time (w/o IO): 21.968ms
        Processing time (w/o IO): 21.888ms
        Processing time (w/o IO): 21.941ms
        Processing time (w/o IO): 22.049ms
        Processing time (w/o IO): 21.762ms
        Processing time (w/o IO): 22.027ms
        Processing time (w/o IO): 21.994ms
        Processing time (w/o IO): 21.678ms
        Processing time (w/o IO): 21.595ms
          Time (mean ± σ):     102.1 ms ±   0.9 ms    [User: 92.5 ms, System: 10.7 ms]
          Range (min … max):   101.1 ms … 104.0 ms    10 runs
         
D:

        Benchmark 1: ./related
        Processing time (w/o IO): 259.086ms
        Processing time (w/o IO): 258.262ms
        Processing time (w/o IO): 258.265ms
          Time (mean ± σ):     556.8 ms ±   1.6 ms    [User: 531.5 ms, System: 29.6 ms]
          Range (min … max):   555.7 ms … 557.9 ms    2 runs
         
D:

        Benchmark 1: ./related
        Processing time (w/o IO): 2128.94ms
        Processing time (w/o IO): 2133.02ms
        Processing time (w/o IO): 2133.61ms
          Time (mean ± σ):      3.075 s ±  0.002 s    [User: 2.976 s, System: 0.105 s]
          Range (min … max):    3.074 s …  3.077 s    2 runs
```

**Comment by cyrusmsk** [comment]
> Faster but I'd like to separate the implementations. You can choose an appropriate name, maybe `d_chunked_opt`.

Maybe call it "d_swar" then?

**Comment by jinyus** [comment]
On second thought, `d_v2` would be great for uniformity if other contributors do the same with another lang. Choice is up to you though.

**Comment by cyrusmsk** [comment]
> On second thought, `d_v2` would be great for uniformity if other contributors do the same with another lang. Choice is up to you though.

Ok, d_v2 is also fine. Just SWAR is the name of the optimization techniques, that was used in this version.

**Comment by cyrusmsk** [comment]
Hi @jinyus
Can we merge this PR?

Also I can see that suddenly some regression happened with Go and D version.
For Go I saw you've changed the version of the lang. But for D - I'm not sure what was changed.
Did you change the VM settings?

Probably after some new language into the Docker - maybe version of LLVM has changed..
I will try to prepare the PR with manual installation of compiler. Will see if it helped.

**Comment by jinyus** [comment]
I was waiting for you to make a separate folder for this PR: `d_v2`. I thought we agreed on that...

I shutdown the VM when not in use as it's getting expensive so it's reallocated everytime I need it. I don't think that's the issue though. Arch usually have the latest versions so it might be an upstream ldc issue. It was recently updated from `3-1.34.0-1` to `3-1.35.0-1`

**Pull request closed without merging**
