### PR TITLE
Add Nim

### PR DESCRIPTION
**Pull request by jinyus**
#54

### CODE REVIEW

**Comment by michaelsbradleyjr** [comment]
Nim's `std/json` is well-known in the community to be on the slow side, and most projects will instead use `jsony` or another faster-than-std lib:

https://github.com/treeform/jsony

**Comment by jinyus** [comment]
Added

**Comment by michaelsbradleyjr** [comment]
> Added

Cool. So, there's some discussion in the Nim community about ways the performance of `related.nim` can be improved while adhering to the rules in this repo's readme and without getting exotic. Are you open to PRs in that regard?

**Comment by jinyus** [comment]
Yes, go for it.

**Pull request merged**
