### PR TITLE
[Nim Con] PGO with gcc, profiled on 60k posts

### PR DESCRIPTION
**Pull request by michaelsbradleyjr**
Changes are for `nim_con` only.

`nim_rev_7` == `nim_con` with gcc PGO 60k
```
Run Benchmark (5k posts)
Running Nim Concurrent
using 4 threads
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 19.161ms
	Processing time (w/o IO): 22.642ms
	Processing time (w/o IO): 19.441ms
	Processing time (w/o IO): 19.226ms
	Processing time (w/o IO): 19.127ms
	Processing time (w/o IO): 19.519ms
	Processing time (w/o IO): 20.306ms
	Processing time (w/o IO): 19.881ms
	Processing time (w/o IO): 19.356ms
	Processing time (w/o IO): 18.953ms
	Processing time (w/o IO): 19.148ms
	Processing time (w/o IO): 18.922ms
	Processing time (w/o IO): 19.931ms
	 Time (mean ± σ):      49.7 ms ±   1.0 ms    [User: 62.8 ms, System: 15.8 ms]
	 Range (min … max):    48.5 ms …  51.6 ms    10 runs
	
Checking output
Success: related_posts_nim_con.json is valid!

Generate 20000 posts
Run Benchmark (15k posts)
Running Nim Concurrent
using 4 threads
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 255.649ms
	Processing time (w/o IO): 254.329ms
	Processing time (w/o IO): 258.073ms
	 Time (mean ± σ):     373.8 ms ±   9.2 ms    [User: 763.4 ms, System: 37.2 ms]
	 Range (min … max):   367.3 ms … 380.3 ms    2 runs

Generate 60000 posts
Run Benchmark (30k posts)
Running Nim Concurrent
using 4 threads
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 2281.08ms
	Processing time (w/o IO): 2281.354ms
	Processing time (w/o IO): 2280.384ms
	 Time (mean ± σ):      2.665 s ±  0.008 s    [User: 6.500 s, System: 0.109 s]
	 Range (min … max):    2.660 s …  2.670 s    2 runs
```

`main` == `nim_con` with clang without PGO
```
Run Benchmark (5k posts)
Running Nim Concurrent
using 4 threads
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 22.048ms
	Processing time (w/o IO): 21.769ms
	Processing time (w/o IO): 21.51ms
	Processing time (w/o IO): 21.755ms
	Processing time (w/o IO): 22.158ms
	Processing time (w/o IO): 22.232ms
	Processing time (w/o IO): 22.278ms
	Processing time (w/o IO): 21.969ms
	Processing time (w/o IO): 21.826ms
	Processing time (w/o IO): 22.218ms
	Processing time (w/o IO): 22.031ms
	Processing time (w/o IO): 21.866ms
	Processing time (w/o IO): 21.843ms
	 Time (mean ± σ):      52.8 ms ±   1.1 ms    [User: 72.9 ms, System: 13.9 ms]
	 Range (min … max):    51.2 ms …  54.4 ms    10 runs
	
Checking output
Success: related_posts_nim_con.json is valid!

Generate 20000 posts
Run Benchmark (15k posts)
Running Nim Concurrent
using 4 threads
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 297.606ms
	Processing time (w/o IO): 298.341ms
	Processing time (w/o IO): 296.255ms
	 Time (mean ± σ):     414.7 ms ±   6.9 ms    [User: 874.9 ms, System: 41.4 ms]
	 Range (min … max):   409.8 ms … 419.6 ms    2 runs
	
Generate 60000 posts
Run Benchmark (30k posts)
Running Nim Concurrent
using 4 threads
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 2677.794ms
	Processing time (w/o IO): 2676.803ms
	Processing time (w/o IO): 2680.33ms
	 Time (mean ± σ):      3.064 s ±  0.006 s    [User: 7.507 s, System: 0.089 s]
	 Range (min … max):    3.060 s …  3.068 s    2 runs
```

### CODE REVIEW

**Comment by michaelsbradleyjr** [comment]
For comparison only, here is gcc *without* PGO for `nim_con`. 

Change to *disable* PGO is not in this PR, but you can/try it on the `nim_rev_7_gcc_without_pgo` branch:

[`nim_rev_7...nim_rev_7_gcc_without_pgo`](https://github.com/michaelsbradleyjr/related_post_gen/compare/nim_rev_7...nim_rev_7_gcc_without_pgo)

The numbers are very close to clang without PGO on `main`, i.e. gcc PGO 60k is better.

```
Run Benchmark (5k posts)
Running Nim Concurrent
using 4 threads
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 22.551ms
	Processing time (w/o IO): 22.348ms
	Processing time (w/o IO): 21.96ms
	Processing time (w/o IO): 23.441ms
	Processing time (w/o IO): 22.381ms
	Processing time (w/o IO): 23.283ms
	Processing time (w/o IO): 22.438ms
	Processing time (w/o IO): 23.313ms
	Processing time (w/o IO): 21.891ms
	Processing time (w/o IO): 21.921ms
	Processing time (w/o IO): 23.184ms
	Processing time (w/o IO): 22.26ms
	Processing time (w/o IO): 21.643ms
	 Time (mean ± σ):      51.9 ms ±   1.4 ms    [User: 73.4 ms, System: 15.7 ms]
	 Range (min … max):    49.9 ms …  54.2 ms    10 runs
	
Checking output
Success: related_posts_nim_con.json is valid!

Generate 20000 posts
Run Benchmark (15k posts)
Running Nim Concurrent
using 4 threads
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 301.445ms
	Processing time (w/o IO): 297.619ms
	Processing time (w/o IO): 302.448ms
	 Time (mean ± σ):     415.2 ms ±   7.1 ms    [User: 908.2 ms, System: 35.3 ms]
	 Range (min … max):   410.2 ms … 420.3 ms    2 runs
	
Generate 60000 posts
Run Benchmark (30k posts)
Running Nim Concurrent
using 4 threads
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 2693.789ms
	Processing time (w/o IO): 2688.033ms
	Processing time (w/o IO): 2677.615ms
	 Time (mean ± σ):      3.067 s ±  0.005 s    [User: 7.725 s, System: 0.099 s]
	 Range (min … max):    3.063 s …  3.070 s    2 runs
```

**Comment by jinyus** [comment]
```
Nim Concurrent:

        Benchmark 1: ./build/related_con
        Processing time (w/o IO): 28.728ms
        Processing time (w/o IO): 28.557ms
        Processing time (w/o IO): 27.311ms
        Processing time (w/o IO): 27.494ms
        Processing time (w/o IO): 27.677ms
        Processing time (w/o IO): 27.797ms
        Processing time (w/o IO): 26.929ms
        Processing time (w/o IO): 28.012ms
        Processing time (w/o IO): 28.028ms
        Processing time (w/o IO): 28.409ms
        Processing time (w/o IO): 26.814ms
        Processing time (w/o IO): 27.968ms
        Processing time (w/o IO): 28.136ms
          Time (mean ± σ):      55.6 ms ±   1.0 ms    [User: 90.2 ms, System: 11.9 ms]
          Range (min … max):    54.2 ms …  57.6 ms    10 runs
         
Checking output
Success: related_posts_nim_con.json is valid!
Generate 20000 posts
Run Benchmark (15k posts)
Running Nim Concurrent
using 4 threads
Nim Concurrent:

        Benchmark 1: ./build/related_con
        Processing time (w/o IO): 378.753ms
        Processing time (w/o IO): 382.783ms
        Processing time (w/o IO): 377.114ms
          Time (mean ± σ):     488.2 ms ±   4.1 ms    [User: 1124.5 ms, System: 35.6 ms]
          Range (min … max):   485.2 ms … 491.1 ms    2 runs
         
Generate 60000 posts
Run Benchmark (30k posts)
Running Nim Concurrent
using 4 threads
Nim Concurrent:

        Benchmark 1: ./build/related_con
        Processing time (w/o IO): 3434.199ms
        Processing time (w/o IO): 3456.673ms
        Processing time (w/o IO): 3436.423ms
          Time (mean ± σ):      3.823 s ±  0.008 s    [User: 9.983 s, System: 0.103 s]
          Range (min … max):    3.817 s …  3.829 s    2 runs
```

**Comment by michaelsbradleyjr** [comment]
Bad luck run? Maybe a typo and you had `BRANCH='nim_rev_6'` i.e. something other than `nim_rev_7`?

I had a normal run (hopefully not wishful thinking) and then a bad luck run right after that, see below.

Trying to think of other things besides the following which could play a factor that could be considered and investigated over time:
* ~different OS/toolchain~ (ruled out now)
* load spikes on VM host
* PGO quality randomly suffering
* code generated by Nim randomly differing re: how well compiler/toolchain can optimize it

Just now in Azure VM
```
docker run -it --rm -e GIT_REPO='https://github.com/michaelsbradleyjr/related_post_gen.git' -e BRANCH='nim_rev_7' -e TEST_NAME=nim_con databench
```
```
Run Benchmark (5k posts)
Running Nim Concurrent
using 4 threads
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 19.891ms
	Processing time (w/o IO): 18.744ms
	Processing time (w/o IO): 19.344ms
	Processing time (w/o IO): 19.707ms
	Processing time (w/o IO): 19.884ms
	Processing time (w/o IO): 19.398ms
	Processing time (w/o IO): 18.789ms
	Processing time (w/o IO): 18.437ms
	Processing time (w/o IO): 19.962ms
	Processing time (w/o IO): 19.324ms
	Processing time (w/o IO): 20.331ms
	Processing time (w/o IO): 19.605ms
	Processing time (w/o IO): 19.338ms
	 Time (mean ± σ):      48.5 ms ±   1.5 ms    [User: 68.3 ms, System: 10.3 ms]
	 Range (min … max):    45.9 ms …  50.4 ms    10 runs
	
Checking output
Success: related_posts_nim_con.json is valid!

Generate 20000 posts
Run Benchmark (15k posts)
Running Nim Concurrent
using 4 threads
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 252.357ms
	Processing time (w/o IO): 252.763ms
	Processing time (w/o IO): 252.793ms
	 Time (mean ± σ):     364.4 ms ±   4.3 ms    [User: 751.6 ms, System: 37.3 ms]
	 Range (min … max):   361.4 ms … 367.4 ms    2 runs
	
Generate 60000 posts
Run Benchmark (30k posts)
Running Nim Concurrent
using 4 threads
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 2273.94ms
	Processing time (w/o IO): 2591.404ms
	Processing time (w/o IO): 2285.477ms
	 Time (mean ± σ):      2.816 s ±  0.214 s    [User: 6.310 s, System: 0.087 s]
	 Range (min … max):    2.665 s …  2.968 s    2 runs
```
Bad Luck after previous good run
```
docker run -it --rm -e GIT_REPO='https://github.com/michaelsbradleyjr/related_post_gen.git' -e BRANCH='nim_rev_7' -e TEST_NAME=nim_con databench
```
```
Run Benchmark (5k posts)
Running Nim Concurrent
using 4 threads
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 27.916ms
	Processing time (w/o IO): 28.482ms
	Processing time (w/o IO): 27.341ms
	Processing time (w/o IO): 27.351ms
	Processing time (w/o IO): 27.83ms
	Processing time (w/o IO): 28.823ms
	Processing time (w/o IO): 28.406ms
	Processing time (w/o IO): 28.012ms
	Processing time (w/o IO): 28.565ms
	Processing time (w/o IO): 28.286ms
	Processing time (w/o IO): 27.955ms
	Processing time (w/o IO): 27.707ms
	Processing time (w/o IO): 27.75ms
	 Time (mean ± σ):      57.9 ms ±   1.1 ms    [User: 90.9 ms, System: 13.5 ms]
	 Range (min … max):    55.9 ms …  59.0 ms    10 runs
	
Checking output
Success: related_posts_nim_con.json is valid!

Generate 20000 posts
Run Benchmark (15k posts)
Running Nim Concurrent
using 4 threads
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 383.622ms
	Processing time (w/o IO): 386.449ms
	Processing time (w/o IO): 385.37ms
	 Time (mean ± σ):     501.6 ms ±   1.4 ms    [User: 1146.8 ms, System: 33.0 ms]
	 Range (min … max):   500.6 ms … 502.6 ms    2 runs
	
Generate 60000 posts
Run Benchmark (30k posts)
Running Nim Concurrent
using 4 threads
Nim Concurrent:

	Benchmark 1: ./build/related_con
	Processing time (w/o IO): 3436.724ms
	Processing time (w/o IO): 3430.434ms
	Processing time (w/o IO): 3430.098ms
	 Time (mean ± σ):      3.819 s ±  0.011 s    [User: 9.973 s, System: 0.099 s]
	 Range (min … max):    3.811 s …  3.827 s    2 runs
```

**Comment by jinyus** [comment]
```
Nim Concurrent:

        Benchmark 1: ./build/related_con
        Processing time (w/o IO): 18.94ms
        Processing time (w/o IO): 18.864ms
        Processing time (w/o IO): 18.696ms
        Processing time (w/o IO): 18.636ms
        Processing time (w/o IO): 19.01ms
        Processing time (w/o IO): 18.747ms
        Processing time (w/o IO): 18.918ms
        Processing time (w/o IO): 20.002ms
        Processing time (w/o IO): 19.022ms
        Processing time (w/o IO): 18.561ms
        Processing time (w/o IO): 19.214ms
        Processing time (w/o IO): 21.761ms
        Processing time (w/o IO): 18.481ms
          Time (mean ± σ):      47.6 ms ±   1.7 ms    [User: 64.3 ms, System: 12.4 ms]
          Range (min … max):    45.7 ms …  51.4 ms    10 runs
         
Checking output
Success: related_posts_nim_con.json is valid!
Generate 20000 posts
Run Benchmark (15k posts)
Running Nim Concurrent
using 4 threads
Nim Concurrent:

        Benchmark 1: ./build/related_con
        Processing time (w/o IO): 257.13ms
        Processing time (w/o IO): 253.851ms
        Processing time (w/o IO): 250.796ms
          Time (mean ± σ):     361.0 ms ±   0.1 ms    [User: 753.0 ms, System: 31.8 ms]
          Range (min … max):   361.0 ms … 361.1 ms    2 runs
         
Generate 60000 posts
Run Benchmark (30k posts)
Running Nim Concurrent
using 4 threads
Nim Concurrent:

        Benchmark 1: ./build/related_con
        Processing time (w/o IO): 2318.007ms
        Processing time (w/o IO): 2275.865ms
        Processing time (w/o IO): 2290.699ms
          Time (mean ± σ):      2.653 s ±  0.008 s    [User: 6.492 s, System: 0.091 s]
          Range (min … max):    2.647 s …  2.658 s    2 runs
```

**Comment by michaelsbradleyjr** [comment]
Did a bit of investigation, nothing conclusive yet:

For a slower run, the `related_con` executable never has a *much* faster run for any randomly generated 5..20..60k `posts.json`, no matter how many times you try it.

For a faster run, the `related_con` executable likewise never has a *much* slower run.

So that completely rules out load spikes on the VM's host, as far as I can tell.

So there is some variability in one/more of these:
* Nim generation of C sources
* C compilation
* PGO in general
* PGO relative to randomness in `posts.json` generated with `gen_fake_posts.py`
* linker
* LTO as special case re: linker

I am trying to get a slower run without PGO (5k runs jump from ~21 ms to ~30/40ms), to check if the above is true for those builds, to rule out PGO, but I haven't triggered one yet, will keep trying over time.

**Pull request closed without merging**
